### ISSUE TITLE
Collaboration suggestion

### ISSUE THREAD

**Issue by Madis0** [badasintended/wthit#1]
Hello, you might want to collaborate with Jade, which has several fixes to HWYLA and is already more popular.

https://github.com/Snownee/Jade/ 

Perhaps you could maintain the Fabric part and they could maintain the Forge one?

**Comment by deirn** [comment]
Adding features isn't my priority for this fork, sorry. About the fixes, I already committed most of them so don't worry about it.

<sub><sub><sub><sub>Also I kinda dislike that Jade doesn't keep the git history but oh well</sub></sub></sub></sub>
