### ISSUE TITLE
Game crashes with WTHIT mod.

### ISSUE THREAD

**Issue by rjuven2401** [badasintended/wthit#100]
### Describe the issue

In the Minecraft launcher (the default launcher when I get after installing Minecraft) I select fabric loader 1.18.1.
If I start the game, about 10 seconds later the crash occurs and game does not start.

Minecraft version: 1.18.1
Fabric Loader version: 0.12.12
[Fabric API](https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/3609610) version: 0.46.1

[Roughly Enough Items Fabric (REI)](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items/files/3632907) version: 7.2.418
[Cloth Config API (Fabric)](https://www.curseforge.com/minecraft/mc-mods/cloth-config/files/3559638) version: 6.1.48
[Architectury API (Fabric)](https://www.curseforge.com/minecraft/mc-mods/architectury-fabric/files/3632975) version: 3.6.15

[WTHIT](https://www.curseforge.com/minecraft/mc-mods/wthit/files/3594970) version: 4.4.1
[Mod Menu](https://www.curseforge.com/minecraft/mc-mods/modmenu/files/3570652) version: 3.0.1

I believe every mods are up-to-date.
If I remove WTHIT mod, the game does not crash and starts fine.

I don't know why, but a friend of mine does not have any problem starting Minecraft and joining the server even if he has the same version of Minecraft, Fabric Loader, Fabric API, and mods. Only I cannot start Minecraft.

### Log output

https://gist.github.com/rjuven2401/dd7891d9d69c3d9082a95fc6a98b854d
I uploaded both crash report and log.

**Comment by rjuven2401** [comment]
Deleting `.minecraft/config/waila/waila.json` does not resolve the problem.

**Comment by rjuven2401** [comment]
Oh, deleting the folder `.minecraft/config/waila/` resolved the problem. Thank you.

**Comment by deirn** [comment]
Oh, it's `waila_plugins.json`, sorry.
