### ISSUE TITLE
Support for 'Slight' GUI Modifications Custom Tooltips

### ISSUE THREAD

**Issue by RyanCR03** [badasintended/wthit#103]
Support for ['Slight' GUI Modifications](https://www.curseforge.com/minecraft/mc-mods/slight-gui-modifications) Custom tooltips

**Comment by deirn** [comment]
What do the custom tooltips actually be?

**Comment by deirn** [comment]
You can already change the color with themes. There's default and dark theme by default but you can make one yourself. See the config at `.minecraft/config/waila/waila.json`.

Closing this as it's unnecessary.
