### ISSUE TITLE
v2.2.1 and v2.3.1 doesn't work, only v2.2.0 and below

### ISSUE THREAD

**Issue by Fogrits** [badasintended/wthit#11]
#### Issue Description:
Mod loads, but overlay doesn't appear

#### What happens:

Same as above

#### What you expected to happen:

Mod's overlay to show

#### Steps to reproduce:

1.  use v2.2.0 = overlay shows and everything works as intended
2.  v.2.2.1 and above = break
3. ?
...

____
#### Affected Versions (Do *not* use "latest"):

- WTHIT: v2.2.1 and v2.3.1
- Minecraft: 1.16.5
- Fabric API: 0.31.0

#### Possible Conflicting Mods (Provide their version, as well)

None that I know about

**Comment by deirn** [comment]
i added an option to disable block tooltip in 2.3.0
open plugin settings > waila core > show blocks
it got disabled when you update to 2.3.0 first because I forgot this line c51ab809d66cd04e7d140b254a699977336c9952
sorry for the confusion
