### ISSUE TITLE
1.18.2 Support

### ISSUE THREAD

**Issue by BaccarWozat** [badasintended/wthit#112]
### Describe the issue

Crashes before title screen.
Fabric 0.13.2, Fabric API 0.47.2, WTHIT 4.5.1.

### Log output

https://gist.github.com/BaccarWozat/920f9cf5eae56271ef6acf8560fef465

### Additional context

Latest.log does not have very much of the info, but the console has this:
```
Description: Initializing game
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'wthit'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
```
(among other lines not in the gist)

Console log: [https://paste.ee/p/KjKOB](https://paste.ee/p/KjKOB)

**Comment by deirn** [comment]
I'll probably wait until a pre-release to try to port it.
