### ISSUE TITLE
Can't connect to 1.18.2 server with vanilla client

### ISSUE THREAD

**Issue by Foxite** [badasintended/wthit#114]
### Describe the issue

Server: 1.18.2 with fabric and wthit
Client: Vanilla
Result:
![Screenshot_20220228_215056](https://user-images.githubusercontent.com/20421657/156056640-c88d680b-3366-4b84-8280-2b245cf3d9d1.png)

### Log output

https://gist.github.com/Foxite/451c5d652901c4e9008fd2f23d9c9ac2

**Comment by deirn** [comment]
Right, I forgot that that scenario exists 😅.
