### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Liam1006** [badasintended/wthit#116]
### Describe the issue

When I install it and put it in the mods folder, It shows this.
![2022-03-06 00_09_48-Minecraft_ 1 18 1](https://user-images.githubusercontent.com/93350644/156910126-7be48aeb-4e4e-4b46-a12e-65daf7cc3a5f.png)

### Log output

Mod folder

### Additional context

Am I missing another mod
![2022-03-06 00_11_12-Settings](https://user-images.githubusercontent.com/93350644/156910151-60b4ef1a-f8b8-45ee-9894-d7ab027baa7f.png)
?

**Comment by deirn** [comment]
Use the correct version for your Minecraft version. Check it on CurseForge.
