### ISSUE TITLE
Container caching

### ISSUE THREAD

**Issue by KTibow** [badasintended/wthit#118]
If the mod isn't on the server, cache the contents of containers when they're opened.

**Comment by deirn** [comment]
WTHIT doesn't even have container tooltip built-in, you probably talking about my other project, Megane, that adds it along with other.

And no, it will always require the server to have it so it can control what the players can see.

**Comment by KTibow** [comment]
Oh, didn't realize that. Sorry.

> so it can control what the players can see.

Interesting point. I don't think it would be OP or anything, but I can see why you could have this type of a philosophy.
