### ISSUE TITLE
Inventory tooltips do not respect "Show Mod Names"

### ISSUE THREAD

**Issue by 0x5c** [badasintended/wthit#12]
#### Issue Description:
WTHIT adds the mod name to inventory tooltips even with the "Show Mod Names" set to off.

WTHIT is confirmed to be the cause since the format string set in WTHIT appears in the tooltip (adding random letters shows in the tooltip

#### What you expected to happen:
I expect WTHIT to not even touch normal item tooltips without there being a config item for it.

#### Steps to reproduce:

1. Turn "Show Mod Names" to off
2. Set a custom format string for mod names, preferably by adding random letters (not needed for bug but needed for demo)
3. Observe the format string being present in all item tooltips

____
#### Affected Versions (Do *not* use "latest"):

- WTHIT: v2.3.0+1.16.5
- Minecraft: 1.16.5
- Fabric API: v0.30.3+1.16

#### Possible Conflicting Mods (Provide their version, as well)
I don't see what other mod could be having this behaviour.

#### Screenshots
![image](https://user-images.githubusercontent.com/5877043/109865905-a5fd9300-7c32-11eb-9203-b9c59fb81221.png)
![image](https://user-images.githubusercontent.com/5877043/109865964-b877cc80-7c32-11eb-8ed5-7501812d8a65.png)
![image](https://user-images.githubusercontent.com/5877043/109865995-c1689e00-7c32-11eb-8707-0c2a1d2a4ba7.png)

**Comment by deirn** [comment]
Honestly yeah, I agree that it shouldn't even have that feature. I'll remove it altogether since I believe REI has mod name tooltip too? When you use waila you probably also use rei anyway.

**Comment by 0x5c** [comment]
That's pretty much what I was thinking, it's already a feature of REI.
