### ISSUE TITLE
Error when looking at horse tamed by Bedrock player (via Geyser and Floodgate)

### ISSUE THREAD

**Issue by SCPRedMage** [badasintended/wthit#120]
### Describe the issue

When looking at a horse tamed by a Bedrock player connected via Geyser and Floodgate, frame rate drops to less than 1 FPS, and an error appears in the WTHIT popup. Logs indicate this is because both the Name and ID provided to mcp.mobius.waila.plugin.vanilla.provider.PetOwnerProvider is blank.
![horse_error](https://user-images.githubusercontent.com/17621208/158515697-9874e2c1-6a48-4179-9f24-7213138061d5.png)

### Log output

https://gist.github.com/SCPRedMage/d1692a94c287213b63abf9659fa5c318

**Comment by deirn** [comment]
Seems to be the same issue as #109, closing this as duplicate.
