### ISSUE TITLE
Change in behavior for Furnace preview now requires sneak

### ISSUE THREAD

**Issue by MeeniMc** [badasintended/wthit#123]
### Describe the issue

In 4.8.0, when using the 'Sneak to show details' config, the Furnace progress bar shows only when sneaking. 

This is a new behavior compared to WTHIT 4.5.5 (and all prior versions): in these versions, sneaky details hides things like block states, but still shows the smelt progress bar. 

The same issue extends to container content when using Megane.

### Log output

https://paste.ee/p/bsFUI

**Comment by deirn** [comment]
Pretty sure that's always been the case for WTHIT's furnace preview, megane replaces it to it's own implementation, it just now changed to also do that.

This is code snippet from a year ago, the preview is added to body part of the tooltip which is the one that hidden when you use sneaky details.
https://github.com/badasintended/wthit/blob/1e472076fbffc575001884020ff48c5827cee3a6/common/src/main/java/mcp/mobius/waila/plugin/vanilla/WailaVanilla.java#L95-L96

**Comment by MeeniMc** [comment]
This is WTHIT 4.5.5 (1.18.1) 

![2022-03-26_07 08 09](https://user-images.githubusercontent.com/68366846/160236787-aad7f396-0672-49ab-8387-513b239b3b5d.png)

**Comment by deirn** [comment]
Do you also have megane in your screenshot?

**Comment by deirn** [comment]
Try without megane then.

**Comment by MeeniMc** [comment]
You are right the change in behavior is in Megane. I still preferred the old behavior (of the combo) though.
