### ISSUE TITLE
Player can see other player inventory

### ISSUE THREAD

**Issue by TheMightyMcGrew** [badasintended/wthit#125]
### Describe the issue

I think the title sums it up. Dont feel like players should be able to see another players inventory unless they are admins or such. If this was intended would at least be nice to have the option to disable that server side. Minecraft 1.18.1 Mod version  4.5.5 Fabric

### Log output

https://gist.github.com/TheMightyMcGrew/efa36281fb1ad5eba15419e47f97ed61

**Comment by deirn** [comment]
It's from megane. You can always add `minecraft:player` to the entity inventory blacklist (on the server, if you want all player to not see each other inventory).
