### ISSUE TITLE
infested, trapped, powder not showing

### ISSUE THREAD

**Issue by timriker** [badasintended/wthit#126]
### Describe the issue

Running 1.18.2 with:
baritone-api-fabric-1.8.3.jar
fabric-api-0.47.10+1.18.2.jar
voxelmap-1.18.2-1.11.1.jar
wthit-fabric-4.8.1.jar
Wurst-Client-v7.23-MC1.18.2.jar

I don't see a menu entry to change config/waila/waila_plugins.json entries override.infested, override.trapped_chest and override.powder_snow.

Setting them to false and restarting Minecraft still does not show powered snow vs snow.

### Log output

https://gist.github.com/timriker/540f654c6d39c771374251f2ab4e132e

**Comment by deirn** [comment]
You need the server to disable the option for it to work (you can see the option missing from the config screen if you play on dedicated server, it'll present on single player).
All of that blocks is designed to be misleading so I made the tooltip too.
