### ISSUE TITLE
Crashing on startup caused by WTHIT

### ISSUE THREAD

**Issue by ghost** [badasintended/wthit#128]
### Describe the issue

Using a fabric with other mods but WTHIT will not allow the game to boot to the Start screen.

### Log output

https://gist.github.com/WeegeeDev204/fc4355246e2f3486e010766b83c7e86f

### Additional context

I've also attached the crash report and mod list https://gist.github.com/WeegeeDev204/80281e62853350c0dba2425eca9b085
![modlist](https://user-images.githubusercontent.com/74462103/163688662-6368dcd8-3be5-48a0-b1ab-6aea23845c80.PNG)
7

**Comment by deirn** [comment]
That's not the full log.
