### ISSUE TITLE
No Inventory content?

### ISSUE THREAD

**Issue by muluffel** [badasintended/wthit#130]
Hi,
I don't know if it's an issue or just a non existing feature (so I labeled it as enhancement, feel free to change) but I wondered that I cant see inventory previews of chests or shulkerboxes. Furnaces work tho. I have both bad packets and WTHIT installed on the client and the server. Am I missing a setting?

**Comment by deirn** [comment]
There's no inventory tooltip from base WTHIT, if you want you can also install [megane](https://www.curseforge.com/minecraft/mc-mods/megane/) which I also make (even before I forked Hwyla into WTHIT, that's the reason I forked it.)
