### ISSUE TITLE
Adding resource pack sprite support

### ISSUE THREAD

**Issue by ghost** [badasintended/wthit#133]
I'm working on my resource pack and when trying to add support for your mod, I noticed that it just doesn't work. Support for other mods works great, but yours just won't accept the sprite from my resource pack. This doesn't look like a bug, so I didn't put it in the bug category. If this is still a bug... Sorry :)

**Comment by deirn** [comment]
What sprite do you want to change? If it's the tooltip background and such, it's changeable via a config file [like this](https://github.com/TeamAOF/All-of-Fabric-5/blob/0261e3b6e3c85b4a3ad9301b66722ac82e8701c5/config/waila/waila.json#L30-L36) and not via a resource pack.

**Comment by ghost** [comment]
I want to replace the furnace arrow sprite.

**Comment by deirn** [comment]
Ah, that. Can you send your resource pack? Remove anything other than the waila folder and the pack.json if you want.

**Comment by ghost** [comment]
My resource pack is open, however I didn't post the new release because I want support for all included mods to work. You can download the resource pack from the link below:

https://drive.google.com/file/d/1vZ8QpLe-K9TSMdC1reO8Ntzptj1ZSvlf/view?usp=sharing

**Comment by deirn** [comment]
Hmm, it looks like it's working for me, so I'm not sure what's wrong with your setup.
![2022-05-14_22 55 28](https://user-images.githubusercontent.com/21150434/168439424-a4d0503f-bf25-4753-bf12-ff86f240956b.png)
(scaled the tooltip to 2x to make it clearer)

**Comment by ghost** [comment]
Okay, I’ll check now, maybe after the update the need feature worked, since at the time of the description of the problem it was relevant. Give my few minutes.

**Comment by ghost** [comment]
<h1 align="center"><img src="https://i.ibb.co/ysWPR4X/untitled.png"></h1>
<p align="center">It still does not work for me, only if I'm do not directly change the mod file...</p>

**Comment by ghost** [comment]
Perhaps I will soon try to find out if there is a conflict with some other mod and maybe record a video to better represent the problem.

**Comment by ghost** [comment]
I think the RebornCore mod might be involved. I noticed that there are problems with it in several mods (for example, in Lamb Dynamic Lights, the settings from the game interface are not saved).

**Comment by ghost** [comment]
<h1 align="center">I found the culprit! Mod <a href="https://www.curseforge.com/minecraft/mc-mods/megane">Megane</a> is to blame for everything!</h1>
<p align="center">To better understand the problem, watch this <a href="https://youtu.be/wr9o9P8teRE">video</a></p>
<p align="center">I'm not sure if this is a problem with one of the mods or both of them at once, so I will duplicate this information on Megane Issues if necessary. What do you think?</p>

<p>PS: Sorry for some blurry video, it's just that my screen has a resolution of 1600*900 and I saved the video in 1920*1080 with scaling to remove the black bars...</p>

**Comment by deirn** [comment]
Ah, right. Megane replaces the furnace tooltip entirely since it provides a more generic progress tooltip.
https://github.com/megane-modules/runtime/blob/1.18/src/main/resources/assets/megane/textures/arrow.png

**Comment by ghost** [comment]
Umm, ok, but any sprites is missing in the Megane mod file... There is only a mod icon. However, I will try to use the paths that you have given me.

**Comment by deirn** [comment]
It's inside another mod (called `megane-runtime`) bundled inside the jar. You can see it by extracting the jar, its inside `META-INF/jars`.

**Comment by ghost** [comment]
Okay, soon I will check how everything works and close Issues.

**Comment by ghost** [comment]
Everything seems to be working well, thanks for the feedback!
