### ISSUE TITLE
Broken block info display with WTHIT

### ISSUE THREAD

**Issue by LolJohn11** [badasintended/wthit#134]
### Describe the issue

The [WTHIT](https://www.curseforge.com/minecraft/mc-mods/wthit-forge) display for the block info when used on tanks is broken:

- No actual tank block name
- Numerous duplicated lines of tank contents meter

I suppose there is some incompatibility here. Is this something that can be fixed from the ITank side?
![2022-05-10_21 34 54](https://user-images.githubusercontent.com/49366383/167698791-c0d4b886-b687-4230-874a-26bb03485324.png)
![2022-05-10_21 35 17](https://user-images.githubusercontent.com/49366383/167698798-84386f36-dc2b-4530-a01d-0550ed492de3.png)

### Log output

https://gist.github.com/LolJohn11/13663d76b94bfd3f1b5f2415363b446a

**Comment by deirn** [comment]
Does it broken if you use HWYLA instead?

**Comment by LolJohn11** [comment]
@deirn it works perfectly with HWYLA. Except for those "B's" at the beginning of the block and mod names, I don't think those should be there.
![2022-05-12_21 41 33](https://user-images.githubusercontent.com/49366383/168146180-92cfdefe-890d-4237-9e91-62f6cb7086d4.png)

**Comment by LolJohn11** [comment]
@deirn I've installed the latest version of the mod with the fix for this issue, but the issue still persists as if nothing changed.

**Comment by deirn** [comment]
Please run `/wailadump` command and send the output here. The file would be on the root of the game directory.

**Comment by deirn** [comment]
Oops, just noticed that the dump generator doesn't work as expected 🤦

**Comment by deirn** [comment]
Fixed for real this time, the block name not being translated is ITank's fault. Tell them to create a language entry for their blocks.

**Comment by LolJohn11** [comment]
Yes, that last update fixed it. I'll contact the ITank devs to fix the rest of it. Thanks!
