### ISSUE TITLE
Fabric 5.1.3 for 1.19 version crashes, error of missing dependency 'badpackets'

### ISSUE THREAD

**Issue by miss-behave** [badasintended/wthit#137]
### Describe the issue

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install badpackets, version 0.1.2 or later.
Unmet dependency listing:
	 - Mod 'wthit' (wthit) 5.1.3 requires version 0.1.2 or later of badpackets, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

Using Fabric Loader 0.14.6 for 1.19

### Log output

https://gist.github.com/miss-behave/537b21a5162c5bb9a64751fc02578b42

**Comment by deirn** [comment]
https://bai.lol/badpackets

![chrome_0zIPQwKHnV](https://user-images.githubusercontent.com/21150434/172614759-40a7437a-d5c5-43ed-b15c-9182db4d45dd.png)

https://bai.lol/badpackets/mr

![chrome_Yzkx0DsubS](https://user-images.githubusercontent.com/21150434/172615116-4fe017b5-4da9-4417-80c2-1742f1d53a2b.png)
