### ISSUE TITLE
Crash on Startup / "No enum constant"

### ISSUE THREAD

**Issue by Regnak85** [badasintended/wthit#138]
### Describe the issue

Trying to Start Minecraft. 

forge-1.18.2-40.1.48
wthit-forge-4.10.3
badpackets-forge-0.1.2

[crash-2022-06-09_17.52.08-fml.txt](https://github.com/badasintended/wthit/files/8871979/crash-2022-06-09_17.52.08-fml.txt)

### Log output

https://gist.github.com/Regnak85/8cc052daf956f19b2ac01227140a2e02

**Comment by deirn** [comment]
Delete your config at `.minecraft/config/waila/waila_plugins.json`.
