### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by letmesuffer** [badasintended/wthit#139]
### Describe the issue

Launching minecraft. Has happened on every version I've used wthit on since 1.16.5. Only solution I've found is getting rid of it.

Crash message:
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'wthit'!
Exit Code: -1

Crash report:
[Uploading crash-2022-06-10_00.28.44-client.txt…]()

### Log output

https://gist.github.com/letmesuffer/949547c716a9d50b8c20976355f6d267

**Comment by deirn** [comment]
Your crash report wasn't finished uploading when you submit the issue, can you upload it again?
