### ISSUE TITLE
suggest: how about show block break progress

### ISSUE THREAD

**Issue by danieltw** [badasintended/wthit#141]
When use pickaxe to break block (ore, tree etc) , can it show the break progress at tooltips ?

This mod show honey level 'tooltip.waila.honey_level'.
If it can also show bee count in beehive, that will be great.

for forge version

**Comment by deirn** [comment]
What Minecraft version you're in? Because the 1.19 already has it (https://github.com/badasintended/wthit/commit/74804637311b6bab782f446f1bd4a150642be7eb).

**Comment by danieltw** [comment]
Minecraft version is 1.18.2
