### ISSUE TITLE
Crash when using tools to break blocks

### ISSUE THREAD

**Issue by AdminHcat** [badasintended/wthit#144]
### Describe the issue

Crash when using diamond tools to break a Stone blocks

### Log output

https://pastebin.com/fsVQRhAS

### Additional context

waila_errors.log :  https://pastebin.com/KPaZs7Wg

https://bytebin.lucko.me/Ny7kQzW4qY

**Comment by deirn** [comment]
Try without inspecio, it contains Quilted Fabric API module which sometimes break regular Fabric API module.

**Comment by AdminHcat** [comment]
great, i solve the problem by deleting inspecio. Thank you
