### ISSUE TITLE
[1.19] [5.4.3] Client crash

### ISSUE THREAD

**Issue by Nosrick** [badasintended/wthit#145]
### Describe the issue

When using only WTHIT, FAPI, ModMenu and BadPackets, the 1.19 client crashes on startup.

Hopefully my Gist works alright.

### Log output

 https://gist.github.com/Nosrick/7df4d621edb27d38ab9fba182e9eda0b

**Comment by deirn** [comment]
It sounds like either your WTHIT or Bad Packets jar is corrupted or so, can you try redownloading those?

**Comment by Mobmaker55** [comment]
WTHIT crashes my client on startup too, even with no mods added, just Forge 41.0.45

**Comment by deirn** [comment]
> WTHIT crashes my client on startup too, even with no mods added, just Forge 41.0.45

That doesn't mean anything to me. Open a new issue with the logs attached.

**Comment by Nosrick** [comment]
This can probably safely be closed. I believe it was an issue that dependencies hadn't been updated correctly, but it seems to be solved.
