### ISSUE TITLE
Does not work on barriers

### ISSUE THREAD

**Issue by Madis0** [badasintended/wthit#146]
### Describe the issue

WTHIT tooltips are not displayed on barriers, regardless of gamemode. Did not find any option for it either.

### Log output

https://www.toptal.com/developers/hastebin/ipuhibisow.yaml

### Additional context

At least creative should show it... But in my opinion actually all gamemodes should, because they are shown on F3 after all.

**Comment by deirn** [comment]
Invisible blocks are blacklisted by default, you can remove them from `.minecraft/config/waila/blacklist.json`. You will also need to do that on the server's side if you play on server.
