### ISSUE TITLE
Bug with the newest version 5.5.0

### ISSUE THREAD

**Issue by ghost** [badasintended/wthit#147]
### Describe the issue

Hello, I was killing a mob and I got kicked from the server.
When I try to open the new menu with F1, the game crashes again.

https://crashy.net/MyVgUDsNw4vwvN1pUcdy

### Log output

https://crashy.net/w8UX8xZJ8Vr1U58KLw9j

**Comment by deirn** [comment]
Can I get the whole log file? Upload it on Gist (https://gist.github.com/).

**Comment by ghost** [comment]
Here please: https://gist.github.com/mrniddala/92c1eeabf597ffa592fdc7fa07221e67

**Comment by deirn** [comment]
That are the crash reports, the log is `.minecraft/logs/latest.log`.

**Comment by ghost** [comment]
Sorry, duh 😵
https://gist.github.com/mrniddala/e145ae38d5bf62d30ad5c51d6a07031e

**Comment by ghost** [comment]
Thanks!
