### ISSUE TITLE
[Feature Request] Automatic repositioning when top-centered while boss bars are on screen

### ISSUE THREAD

**Issue by Abbanon** [badasintended/wthit#15]
Not sure if something like this would even be possible, but it would be cool to have as a feature.

Basically, if WTHIT detects a boss health bar on the top of the screen while it's aligned to the top-center, it will move down by 25 on the Y axis automatically to prevent obstruction.

Here's an example of default top-center alignment:
![default](https://user-images.githubusercontent.com/37251822/111907909-93a29800-8a2d-11eb-97f2-1e00674bd3c4.png)

Here's an example with top-center alignment with the Y axis at 25 for 1 boss bar:
![+25 on y axis](https://user-images.githubusercontent.com/37251822/111907943-ba60ce80-8a2d-11eb-9bf0-ac9bd3092085.png)

Here's an example with top-center alignment with the Y axis at 50 for 2 boss bars:
![+50 on y axis](https://user-images.githubusercontent.com/37251822/111907967-ca78ae00-8a2d-11eb-86dc-d315ed8c8ca2.png)

**Comment by koelle25** [comment]
Sorry, Off-Topic:
Hey @Abbanon, what is the Plugin/Mod you use to show the Server statistics at the top left? I did a quick search on CurseForge with different keywords but couldn't find this exact display.

**Comment by Abbanon** [comment]
@koelle25 
That mod is called MiniHUD. (https://www.curseforge.com/minecraft/mc-mods/minihud)
