### ISSUE TITLE
Waila has failed to load correctly

### ISSUE THREAD

**Issue by Dustynzzz** [badasintended/wthit#150]
### Describe the issue

Minecraft version 1.19
Forge versione: 41.0.88
mod version: i tried every version from 5.4.0 to 5.6.1
mod error:  java.lang.NoClassDefFoundError:net/minecraftforge/client/event/ClientPlayerNetworkEvent$LoggedInEvent

[crash-2022-07-16_18.18.49-fml.txt](https://github.com/badasintended/wthit/files/9126184/crash-2022-07-16_18.18.49-fml.txt)
[latest.log](https://github.com/badasintended/wthit/files/9126185/latest.log)

### Log output

.

### Additional context

the last version doesnt work on my forge coz need a newest version that i cant use for other mod

**Comment by deirn** [comment]
> the last version doesnt work on my forge coz need a newest version that i cant use for other mod

Well there's nothing I can do about that, blame Forge for breaking mods. Same-day release doesn't mean anything if you break the API on later update (especially weeks after release).

You can try using Forge 4.0.63, WTHIT 5.5.1 should work with it. You probably need to downgrade other mods.

**Comment by Dustynzzz** [comment]
ok thx a lot
