### ISSUE TITLE
[1.19] [WTHIT 5.6.1] [Quilt Loader 0.17.0] Mod Dependency Error

### ISSUE THREAD

**Issue by OriginCode** [badasintended/wthit#151]
### Describe the issue

![Image](https://user-images.githubusercontent.com/17294071/179702642-1d46da0d-a9af-457c-92a4-33f3ddd48e3d.png)

### Log output

https://gist.github.com/OriginCode/a1906de75090f70056619e78e4f9f2a5

**Comment by deirn** [comment]
Pretty sure the issue template asks for the full `latest.log`.

**Comment by OriginCode** [comment]
> Pretty sure the issue template asks for the full `latest.log`.

This is the full `latest.log` on my machine.

**Comment by deirn** [comment]
Do you have [Quilted Fabric API](https://www.curseforge.com/minecraft/mc-mods/qsl) on your mods folder?

**Comment by OriginCode** [comment]
> Do you have [Quilted Fabric API](https://www.curseforge.com/minecraft/mc-mods/qsl) on your mods folder?

Ah I see, I did not have this mod. Thank you for solving my problem. Closing issue.
