### ISSUE TITLE
Crash On World Join

### ISSUE THREAD

**Issue by ghost** [badasintended/wthit#152]
### Describe the issue

Crashes upon joining the world, with the following error:

<div align="center">

![image](https://user-images.githubusercontent.com/24266948/180202575-144ee125-3020-447b-b409-97c7f4b89c9b.png)

</div>

### Log output and crash report

https://gist.github.com/Brittank88/480b61e2bfd91c17098a744cbcd27c6d

### Additional context

There is no crash report, and I cannot open a world to generate one via F3+C.

**Comment by ghost** [comment]
Realising that this may be caused by Bad Packets itself - please let me know if this is the case!

**Comment by deirn** [comment]
`method_38546` is related to lighting update, it might not be a WTHIT issue. Does it crash without WTHIT (and Bad Packets)?

**Comment by ghost** [comment]
No, it does not.

**Comment by ghost** [comment]
Nevermind, I'm stupid, it actually _is_ crashing without WTHIT, BadPackets or Megane enabled.

Now I'm stumped, is there any way at all to trace what might be causing this? It would be a very large binary search if I had to do it that way.

What confuses me is that it did not do this before and very little has changed to the mod set since.

**Comment by ghost** [comment]
I have found the root cause: ForgetMeChunk

Will raise an issue with the dev/s.
