### ISSUE TITLE
WTHIT should show whats inside Storage Drawers

### ISSUE THREAD

**Issue by randolfE** [badasintended/wthit#153]
I, i recently switched from HWYLA to WTHIT and was expecting the same behaviour.
When looking at the different drawers from the mod Storage Drawers it seems that WTHIT does NOT show whats inside the drawers.
(https://www.curseforge.com/minecraft/mc-mods/storage-drawers)
It would be much apreciated if you could enable it somehow.

(This is also already mentioned in the discussion page on curseforge)

Best regards,
Randolf

**Comment by Geethebluesky** [comment]
I have a similar request for MattiDragon's Extended Drawers: https://www.curseforge.com/minecraft/mc-mods/extended-drawers

Yes, you can see the icons on the drawers, but it'd be nice to be able to see the properties WTHIT might otherwise be able to tell you like mod author, item ID...

**Comment by Seceroth** [comment]
To illustrate the problem with Extended Drawers:
![Knipsel](https://user-images.githubusercontent.com/20866237/190836427-842526e5-5f49-476f-a869-217bf92f3f1f.PNG)
That's four different seeds. Can't really tell what is what without removing them.

https://github.com/MattiDragon/ExtendedDrawers/issues/22#issuecomment-1250289308

**Comment by jarincodes** [comment]
Is there any update on whether or not Extended Drawers will be supported in order to show the name of the item(s) that are in the drawers?
