### ISSUE TITLE
1.19.2 server crash at launch

### ISSUE THREAD

**Issue by Daltaxy** [badasintended/wthit#161]
### Describe the issue

First, I wanna say that even if "waila" is written in the log, it's wthit because apparently it uses the same id ? that's what I saw in the mods list in game, in client side.
My server crashes every time at launch, without closing the server however, it just stops loading.
1.19.2, latest forge loader version, latest mod version. (5.11.3)

### Log output and crash report

https://gist.githubusercontent.com/Daltaxy/46a7cc23177b64a951b88467aa068ffb/raw/71a01bb109248fd4e744635c826826e02f71ab28/debug.log

**Comment by Daltaxy** [comment]
crash report : https://gist.github.com/Daltaxy/042880ffe8c273d3e2919425852eafda#file-crash-2022-08-24_14-59-15-fml-txt
I'm sorry, I miscliked into publishing.

**Comment by deirn** [comment]
This looks like an AE2 issue, try opening an issue there.

**Comment by Daltaxy** [comment]
> This looks like an AE2 issue, try opening an issue there.

Thank you. my bad.
