### ISSUE TITLE
Harvestability Plug-in / Implementation

### ISSUE THREAD

**Issue by Vinidia** [badasintended/wthit#162]
A nice addition to this wonderful mod would be the innate implementation of being able to see whether a block can or cannot be harvested with the current tool. 

For example, a line could be added (optional in settings) saying something like:

"Can Harvest?  |  yes/no (or check/x)"

I know that other mods- which this is a fork of- have plug-ins dedicated to this. But could not find something specifically for my favorite implementation: WTHIT. 

Thank you! <3

**Comment by deirn** [comment]
On Fabric, use **cAn i MiNe thIS bLOCk?**, [[CurseForge]](https://www.curseforge.com/minecraft/mc-mods/can-i-mine-this-block) [[Modrinth]](https://modrinth.com/mod/can-i-mine-this-block). It should really be tagged to require WTHIT..., _\*cough\* @shedaniel_

For Forge I forked Waila Harvestability and updated it to use WTHIT API, [[CurseForge]](https://www.curseforge.com/minecraft/mc-mods/wthit-harvestability) [[Modrinth]](https://modrinth.com/mod/wthit-harvestability).
