### ISSUE TITLE
waila (waila) encountered an error during the side_setup event phase

### ISSUE THREAD

**Issue by AndresF754** [badasintended/wthit#163]
### Describe the issue

Recently updated to the 1.19.2 version, updated all my mods, but waila/wthit error crashes the game

Crash report:

[crash-2022-09-01_11.36.08-fml.txt](https://github.com/badasintended/wthit/files/9471369/crash-2022-09-01_11.36.08-fml.txt)

Latest log:

[latest.log](https://github.com/badasintended/wthit/files/9471374/latest.log)

### Log output and crash report

Crash Report:  [crash-2022-09-01_11.36.08-fml.txt](https://github.com/badasintended/wthit/files/9471369/crash-2022-09-01_11.36.08-fml.txt)            Latest Log: [latest.log](https://github.com/badasintended/wthit/files/9471374/latest.log)

### Additional context

Removed Optifine and still does not work, removed wthit+badpackets and game works correctly, already tried deleting the .minecraft folder aswell as the waila config folder and reinstalling the game and does not work, still getting the crash error, I also tried to use an older yet compatible version of the mod but nothing works

Mod worked perfectly in 1.18.2 with the exact same mods

**Comment by deirn** [comment]
[Update JourneyMap](https://www.curseforge.com/minecraft/mc-mods/journeymap/files/3927230).

**Comment by AndresF754** [comment]
> [Update JourneyMap](https://www.curseforge.com/minecraft/mc-mods/journeymap/files/3927230).

Thank you so much, it worked

**Comment by DavidX2BR** [comment]
I'm having the same problem here, I'm using latest version 5.8.5 JM and Wthit 5.12.0.
https://pastebin.com/raw/BKE9CF8j - Crash Here

**Comment by deirn** [comment]
> I'm having the same problem here, I'm using latest version 5.8.5 JM and Wthit 5.12.0. https://pastebin.com/raw/BKE9CF8j - Crash Here

Can't you read the whole thread?

**Comment by DavidX2BR** [comment]
I'm sorry but I didn't understand the question

**Comment by deirn** [comment]
Scroll up, read all the messages for this issue. I already posted the solution.
