### ISSUE TITLE
Game crashes when I look at a gem from Silent's Gems.

### ISSUE THREAD

**Issue by int-72h** [badasintended/wthit#165]
### Describe the issue

I looked at a silent tools gem ore whilst mining, and now I can't go into that server due to the client crashing as soon as I log in.

### Log output and crash report

https://gist.github.com/int-72h/8a352c902fb93aad38afd3f09570bc79

**Comment by deirn** [comment]
Your WTHIT version is way behind... I remember fixing this like a year ago.
