### ISSUE TITLE
Renamed Containers don't show their changed name in the tooltip.

### ISSUE THREAD

**Issue by Etrit1** [badasintended/wthit#166]
### Describe the issue

I honestly seem to remember this being an issue with WHILIA or whatever also.. and I THINK I remember the mod dev of that saying there was no way to fix it.

But, I'm not sure so I figured I'd check here!

It looks like the tooltip is calling entity info shows up in F3.

Is there a way to make it call whatever the entity tag that shows up when you ACTUALLY open the container?  Ergo, you open a named container and it shows you the name you gave it. 

### Log output and crash report

None

**Comment by deirn** [comment]
The custom name only available if you have WTHIT in the server side as the tag doesn't get synced everytime. There's no reasonable way to get it with client-only.
