### ISSUE TITLE
Description: Mod loading error has occurred

### ISSUE THREAD

**Issue by dodi2020** [badasintended/wthit#167]
### Describe the issue

when loading, it seems as though it finishes, but then it shows an error message and crashes
mod version: Forge 1.16.5

### Log output and crash report

https://gist.github.com/CoolGo1425/f7633f4dcd7bdc0c5734a64c8a2cc5ff

**Comment by deirn** [comment]
Try deleting the config folder at `.minecraft/config/waila`.
