### ISSUE TITLE
ArrayIndexOutOfBoundsException: Array index out of range

### ISSUE THREAD

**Issue by AstromanGaming** [badasintended/wthit#173]
### Describe the issue

Hello, the game crashed when I opened a world. If I remember correctly before reopened the world, I was playing and when (I think) an item fell, the game crashed like this.

I don't know how to reproduce it. But it's possible that it's random. So, there you go.

Also, it is possible that this is caused by one or more third party mods, because I have about 215 mods.

### Log output and crash report

https://gist.github.com/AstromanGaming/bfb0086ed9818498e577f098e90c576d

### Additional context

Not Enough Crashes

**Comment by Joniator** [comment]
We have this bug as well, the only thing that seems to change is the index itself.

The crash reports are some with, some without wthit-plugins: https://gist.github.com/Joniator/adc689ef4a33ef2b091947793362c98e

Another thing that stands out is that imediatly befor the crash JEI throws an exception right before WTHIT crashes:
https://gist.github.com/Joniator/adc689ef4a33ef2b091947793362c98e#file-jei-exception

**Comment by deirn** [comment]
[Try this](https://github.com/badasintended/wthit/actions/runs/3459739084), use the jar without api or sources suffix. My guess is `Register.get` got called multiple times simultaneously, it might be a threading issue.

**Comment by OriginCode** [comment]
Got the same error message, the crash report created by Not Enough Crashes suggests potential causes: Quilt Lifecycle Events, Wthit.

Before I updated my modpack today I did not have this message, I guess it has something to do with recent changes in Quilted Fabric API or Quilt itself.

For reference:
- Crash report: 
[crash-2022-11-15_17.32.08-client.txt](https://github.com/badasintended/wthit/files/10017372/crash-2022-11-15_17.32.08-client.txt)

**Comment by deirn** [comment]
@OriginCode did you try the file I linked above? If not, please try it and let me know if my changes fixed it.

**Comment by OriginCode** [comment]
> @OriginCode did you try the file I linked above? If not, please try it and let me know if my changes fixed it.

Yep, it works, LGTM.
