### ISSUE TITLE
Random Crash when looking at blocks

### ISSUE THREAD

**Issue by ghost** [badasintended/wthit#174]
### Describe the issue

Client crash when looking on any block. (only sometimes and can really be any block)

### Log output and crash report

https://gist.github.com/vertical19991/332e6d1aef0a1288b55ebfcddb6f9018
https://gist.github.com/vertical19991/b54e279fd2380b0c787cdc36a5e2df04

**Comment by znopp** [comment]
Having same issue. Fabric server, I am running WTHIT and server is not. There is absolutely nothing in the logs that suggests that WTHIT is causing this, but it is. 

[Log](https://paste.gg/p/anonymous/d3b027cf6e3a4eb6a6ac2e0764016958)
Note: Disconnect happens @ line 841, 20:21:05

**Comment by deirn** [comment]
Does it crashes or does it only disconnect from server?

**Comment by znopp** [comment]
Disconnect from server
