### ISSUE TITLE
Beehive honey level showing twice.

### ISSUE THREAD

**Issue by StockiesLad** [badasintended/wthit#175]
### Describe the issue

The title says it all.

### Log output and crash report

https://gist.github.com/FluffyBumblebees/a9581e39970443fa8bbac0fdfb391054

### Additional context

![image](https://user-images.githubusercontent.com/60066663/209423902-f03f06e2-10d4-4666-be69-6d4aef7a1afc.png)

**Comment by deirn** [comment]
`honey_level` is from the block states tooltip while `Honey Level` is from standalone option.
My view for the block states tooltip is for debugging purposes, kinda like advanced tooltip for items. It's bound to create a duplicate with a specialized tooltip.

What do you think it should do?

**Comment by StockiesLad** [comment]
I like using block states for stairs and such as it is pretty nice being able to see all of the data. I personally think that the blockstates should have be written in standard title format. Instead of "facing", it's "Facing" & so on. But I'm more then happy to disable the seperate honey level tooltip bc I prefer blockstates.
