### ISSUE TITLE
Server log (Polymer plugin)

### ISSUE THREAD

**Issue by sternschnaube** [badasintended/wthit#176]
### Describe the issue

Hello, I was providing the log via Pastebin.
No server crash, just a log.

### Log output and crash report

https://pastebin.com/raw/USuGk2sH

**Comment by deirn** [comment]
Seems to be this bug that was fixed, https://github.com/Patbox/polymer/pull/52. Try the latest version of Polymer.

**Comment by sternschnaube** [comment]
Oh, I had not even Polymer installed.
Thank you - everything is fine now.
