### ISSUE TITLE
Crashes upon joining world

### ISSUE THREAD

**Issue by Bjorndory** [badasintended/wthit#181]
### Describe the issue

Hi, sorry in advance if the fix is super obvious; I'm new to putting modpacks together. 

My Minecraft crashes on 'Joining World' with WTHIT installed, and turning it, Jade, and WMITAF makes the world load fine. 

### Log output and crash report

https://gist.github.com/Bjorndory/544e65d1a41cb67727f1e7643b07f634

**Comment by deirn** [comment]
WMITAF issue, report it there.

**Comment by Bjorndory** [comment]
Uh... well, thanks for being a bit rude. I only wanted advice, you could have been nicer.
