### ISSUE TITLE
AE2+addon and mekanism comaptability issue

### ISSUE THREAD

**Issue by trashBagFromNowhere** [badasintended/wthit#184]
### Describe the issue

AE2+(applied mekanistics addon) pattern provider and ME interface show empty storage levels of mekanism fluids, gases, infuse types, slurries and pigments.

![2023-01-18_15 34 35](https://user-images.githubusercontent.com/114228777/213172822-44d86a34-12fb-4c94-a14c-555a1453a63c.png)

### Log output and crash report

...

**Comment by deirn** [comment]
Please open another issue with the log output attached.
