### ISSUE TITLE
Show tooltip for target behind blacklisted entity

### ISSUE THREAD

**Issue by FibreTTP** [badasintended/wthit#187]
Adding an entity id to entityTypes in waila/blacklist.json successfully hides the tooltip for that entity. However, the block/entity behind the blacklisted one is not shown.

Would it be possible to check for when a targeted entity is blacklisted, and if so, show the tooltip for something behind it?

Before blacklisting:
![image](https://user-images.githubusercontent.com/120446961/216626683-3b6b07dc-e9eb-424a-b8ca-133eee7807dd.png)

After blacklisting:
![image](https://user-images.githubusercontent.com/120446961/216626767-9b9b1a3c-fdb9-4866-b10e-603c141f15a3.png)

**Comment by deirn** [comment]
![2023-03-02_21 39 36](https://user-images.githubusercontent.com/21150434/222460160-32b6cac2-32c3-470b-9e3c-32f90048bf6f.png)

![2023-03-02_21 39 41](https://user-images.githubusercontent.com/21150434/222460030-6a8a4053-1b86-4e17-be24-82ad4de2afe4.png)
