### ISSUE TITLE
Error when attempting to join worlds

### ISSUE THREAD

**Issue by Beck869** [badasintended/wthit#189]
### Describe the issue

Downloaded WTHIT and when I opened up Minecraft it took a long, long time to load the Mojang screen, so long that I originally opened the GitHub page to report that it wouldn't load past that. I closed and reopened Minecraft then left it on for a few minutes and came back to the main menu loaded, so I tried to join a server and instantly got an error,
![image](https://user-images.githubusercontent.com/21157733/222323888-74403bb2-c9a2-4493-8c3f-30df32d9a096.png) 
so I tried joining other servers, and then my single-player worlds and none of them will open, it just shows the same error message.

I do have a few other mods, but only mods I've previously used that have had no compatibility problems with WTHIT. 

### Log output and crash report

https://gist.github.com/Beck869/d693f5dc60f9734379932fc5766b437b

**Comment by deirn** [comment]
Try with Bad Packets 0.3, 0.4 is only tested on 1.19.4 snapshots.

**Comment by Beck869** [comment]
This worked! Thank you :)
