### ISSUE TITLE
Feature: New Logo

### ISSUE THREAD

**Issue by koelle25** [badasintended/wthit#19]
Hey @deirn,

thanks for continuing the heritage of this mod! Also I like your attitude :grin: 

Regarding the current logo: It is a bit crazy. Although I assume you tried to adapt and exaggerate the style of HWYLA and Waila, a Logo in line with your other mods may be really cool.

So I tried a bit with different ideas, e.g. text only:
![Text only](https://user-images.githubusercontent.com/915514/114313535-2bf4df80-9af7-11eb-97d6-efcaeb56eaaf.png) ![Even simpler text only](https://user-images.githubusercontent.com/915514/114313544-3616de00-9af7-11eb-9dc7-5bfce17b228d.png)

Then some faces:
![angry face 1](https://user-images.githubusercontent.com/915514/114313584-59418d80-9af7-11eb-82d1-df4b7d9558b9.png) ![angry face 1](https://user-images.githubusercontent.com/915514/114313594-5e9ed800-9af7-11eb-8779-666a645c03c2.png) ![surprised face 1](https://user-images.githubusercontent.com/915514/114313636-7f672d80-9af7-11eb-99b2-be2a759d3719.png) ![surprised face 2](https://user-images.githubusercontent.com/915514/114313607-69596d00-9af7-11eb-9b1b-773554e35adc.png) ![surprised face 3](https://user-images.githubusercontent.com/915514/114313653-97d74800-9af7-11eb-9e6b-4b45db44a781.png)

I even tried a 3D-Block icon:
![3D block question](https://user-images.githubusercontent.com/915514/114313789-42e80180-9af8-11eb-8b8c-078cf1479d0f.png) ![3D block wthit](https://user-images.githubusercontent.com/915514/114313723-ea186900-9af7-11eb-84af-e02a2856587a.png)

But then I had a really good inspiration while looking at the Waila logo:
![magnifying glass](https://user-images.githubusercontent.com/915514/114313750-10d69f80-9af8-11eb-84b5-031087099c8a.png)

I like the last one the best. What do you think?

**Comment by deirn** [comment]
ahaha i like the silly face one, but i think I'll keep this logo, sorry. it's from [hwyla](https://github.com/TehNut/HWYLA/blob/1.16_fabric/src/main/resources/assets/waila/logo.png) that never got into modmenu because wrong metadata value 😂. it's also part of the joke (i think)
