### ISSUE TITLE
Position`s edit x and y don`t work.

### ISSUE THREAD

**Issue by Nidre** [badasintended/wthit#2]
#### Issue Description:
Position`s edit x and y don`t work.

#### What happens:
Nothing.

#### What you expected to happen:
Change the position.

____
#### Affected Versions (Do *not* use "latest"):

- Wthit-2.1.1-1.16.5
- Fabric: 1.16.5 (0.11.1)

**Comment by deirn** [comment]
Well that was an embarrassing one
