### ISSUE TITLE
Crash when clicking Plugin Settings

### ISSUE THREAD

**Issue by MScott7** [badasintended/wthit#200]
### Describe the issue

The game crashes upon clicking the Plugin Settings button, complaining about a non [a-z0-9/._-] character in a path. 

### Log output and crash report
crash report: 
https://gist.github.com/MScott7/69ff8e6caeeb64856c0026f03d9648d2
latest.log: 
https://gist.github.com/MScott7/24cd932f4d02cbdf29427993951219ce

### Additional context

Reproducible for me from the main menu and in a world.

**Comment by deirn** [comment]
Seems to be an issue with Visual Overhaul mod on how it looks for button translation key. I'm not sure what's wrong with it though. Either way, doesn't seem to be on WTHIT's side.

https://github.com/TeamMidnightDust/VisualOverhaul/blob/c6ccdb0d95eed61965d9ae0c5e094220c1c394fb/common/src/main/java/eu/midnightdust/visualoverhaul/IconicButtons.java#L31

CC: @Motschen
