### ISSUE TITLE
Crash when looking at block

### ISSUE THREAD

**Issue by BeefyAndTheDucks** [badasintended/wthit#202]
### Describe the issue

Whenever I look at a block, my game crashes.

### Log output and crash report

Crash Report: https://gist.github.com/BeefyAndTheDucks/5bc0641d77c7818f4d2c1c197b320cf4
latest.log: https://gist.github.com/BeefyAndTheDucks/c9f31c2ba5141e11756f13efec421388

**Comment by deirn** [comment]
You appear to have Jade plugin, either use Jade instead of WTHIT or uninstall "Ultimate Plane Mod".
Either way, 1.18 is unsupported.
