### ISSUE TITLE
Crash when using 5.16.0 or newer on Fabric 1.19.2

### ISSUE THREAD

**Issue by NolanHewitt** [badasintended/wthit#204]
### Describe the issue

Using 5.16.0 or 5.16.1 results in a crash on start up. 5.15.5 does not have this issue.

### Log output and crash report

https://gist.github.com/NolanHewitt/0a8c51ee5a8e4afab4e18efeb2277fc6

**Comment by deirn** [comment]
Will be fixed in megane's side. 
https://github.com/badasintended/megane/issues/60
