### ISSUE TITLE
Crash on Launch, 1.19.2

### ISSUE THREAD

**Issue by Morphyloon** [badasintended/wthit#205]
### Describe the issue

Version 5.16.1 (and 5.16.0) crashes on launch, have to roll back to the last stable version of 5.15.5

### Log output and crash report

https://gist.github.com/Morphyloon/5341ae54ad14372eec607faa1def4375

https://gist.github.com/Morphyloon/9ecc76d3477fb9fed89cc472c60f4335

**Comment by deirn** [comment]
Will be fixed on megane' side.
https://github.com/badasintended/wthit/issues/204 https://github.com/badasintended/megane/issues/60
