### ISSUE TITLE
Display contents of Chiseled Bookshelf

### ISSUE THREAD

**Issue by rayaman** [badasintended/wthit#208]
I think it would be a nice addition to the mod if It could display what's inside of the Chiseled Bookshelves.

**Comment by deirn** [comment]
That would probably wait until I finish the API to attach storage information an such, see [`exp/extra`](https://github.com/badasintended/wthit/tree/exp/extra) branch for the progress.

**Comment by deirn** [comment]
What would you imagine the book display looks like?

**Comment by rayaman** [comment]
Is it possible to know which book in the bookcase you are looking at?

I know you can grab an individual book so perhaps getting info on which book is being looked at might be the best way to go. This way it won't be too much info on screen at a time.

For an enchanted book I think the first enchantment with level should be displayed. and perhaps the number of enchants on the book. Perhaps have it cycle through each enchantment while you hover over that book.

For the other books we could display the title/name of it and author if it is a signed book.

If we cannot detect which book is being directly hovered over maybe it could cycle through each book and display the info above with an index of which book is being displayed, or perhaps display a row or column at a time. With each books info.

Maybe it could show up like this if we can target a single book:
```
Enchanted book
Protection IV, Efficiency V
Thorns II 
```

Would probably have to play around with wrapping of the enchantments and level to see how it all fits on the display.

If we cannot target a single book we could abbreviate enchantment names and use a number for their level instead of roman numerals. Or just show the first enchantment for each book that is enchanted and titles/names and author of other books.
```
[EB] Proc 4... | [BQ] Hero's Journal Vol 2 | [B] Book
[B] Hero's Journal Vol 1 | Empty | Empty
``` 
The brackets could be an icon of the type of book you are looking at or are in the bookshelf.

These are just some ideas. I'm not sure how well I expressed them, let me know if I should clarify something better.
