### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Sunconure11** [badasintended/wthit#209]
### Describe the issue

Basically what it says on the tin

### Log output and crash report

https://gist.github.com/Sunconure11/4450130ec16f72a148c83444b13d8b35

### Additional context

Noticed this after updating the mod.

**Comment by deirn** [comment]
Can you send the WTHIT and Bad Packets jar that you use?

**Comment by Sunconure11** [comment]
[stuff.zip](https://github.com/badasintended/wthit/files/11725411/stuff.zip)

**Comment by deirn** [comment]
Looks fine, and it runs fine on my setup. Can you try running with only WTHIT, Bad Packets, and Quilted Fabric API? Try both in the same instance and a new one, it might be loader issue.

**Comment by Sunconure11** [comment]
Works fine with just those three. Does not work in the modpack. I suspect an incompat issue.

**Comment by Sunconure11** [comment]
[crash-2023-06-13_18.00.02.7826-quilt_loader.txt](https://github.com/badasintended/wthit/files/11739855/crash-2023-06-13_18.00.02.7826-quilt_loader.txt)

Crash is still happening on my WIP modpack. But this crash is not present on a clean instance of MC.

**Comment by deirn** [comment]
Something is loading the Log4J class too early, which can only be done in a mixin plugin AFAIK.
I suspect that some mod's mixin plugin loads a library that uses Log4J, you will need to do a binary search by disabling half the mods and see if it still errors out, and halving the erroring half again.

I'm not sure what I can do on WTHIT side, the issue doesn't come from WTHIT as it loads from the correct classloader, it just happens that WTHIT initializer is called first, if it doesn't error with WTHIT it'll error from other mods. I can try moving away from Log4J altogether, but that doesn't really fix the issue.

**Comment by Sunconure11** [comment]
Do you know of any mods offhand that use it? Just so I can narrow things slightly

**Comment by Sunconure11** [comment]
Decided to try Jade out briefly, just to see if it would act as a bandaid fix while we work this out, and ran into this. It is possible something in here is relevant.

https://gist.github.com/Sunconure11/4152c5dfccc888ac548e975987aed851

**Comment by deirn** [comment]
> Decided to try Jade out briefly, just to see if it would act as a bandaid fix while we work this out, and ran into this. It is possible something in here is relevant.
> 
> https://gist.github.com/Sunconure11/4152c5dfccc888ac548e975987aed851

Seems to be the same underlying issue.

Just to make sure, can you try with older Quilt Loader version? It's common for mixin plugins to use Log4J and it should work fine. Also, try with Fabric Loader instead.

**Comment by Sunconure11** [comment]
I'm gonna see if the Fabric version of the mod suffers from the same error or not, first. I have several mods that are Quilt-exclusive, so I would need to make another instance that is Fabric only.

**Comment by Sunconure11** [comment]
[latest.log](https://github.com/badasintended/wthit/files/11751044/latest.log)

**Comment by Sunconure11** [comment]
https://www.curseforge.com/minecraft/mc-mods/kubejs-botania

This mod appears to have issues with this mod... somehow. Investigating further.

**Comment by Sunconure11** [comment]
It's Valkyrien Skies. Adding that back restarted the crash all over again.

**Comment by Sunconure11** [comment]
KubeJS Botania can also set off an error that blames KubeJS.

**Comment by Sunconure11** [comment]
[crash-2023-06-14_18.56.20.7613-quilt_loader.txt](https://github.com/badasintended/wthit/files/11751167/crash-2023-06-14_18.56.20.7613-quilt_loader.txt)
[crash-2023-06-14_18.58.18.3759-quilt_loader.txt](https://github.com/badasintended/wthit/files/11751168/crash-2023-06-14_18.58.18.3759-quilt_loader.txt)
[crash-2023-06-14_19.00.37-client.txt](https://github.com/badasintended/wthit/files/11751169/crash-2023-06-14_19.00.37-client.txt)
[crash-2023-06-14_18.37.36-client.txt](https://github.com/badasintended/wthit/files/11751170/crash-2023-06-14_18.37.36-client.txt)
[crash-2023-06-14_18.41.43-client.txt](https://github.com/badasintended/wthit/files/11751171/crash-2023-06-14_18.41.43-client.txt)
[crash-2023-06-14_18.45.39-client.txt](https://github.com/badasintended/wthit/files/11751172/crash-2023-06-14_18.45.39-client.txt)
