### ISSUE TITLE
The Beetroot doesn't display the right waila

### ISSUE THREAD

**Issue by dexula** [badasintended/wthit#212]
### Describe the issue

The problem could be the fact that I have a lot of mods enabled. However, I am reaching out just in case this is a bug for everyone as well. I'm not sure what to add other than the screenshot of me discovering it one day as well as the waila logs.

### Log output and crash report

https://gist.github.com/dexula/f8cebdf378570b4bb1746bbc277f12ca

### Additional context

![image](https://github.com/badasintended/wthit/assets/116233696/8e2e8fc2-2def-47d2-a3f5-c97f30d14231)

**Comment by deirn** [comment]
Duplicate of #210
