### ISSUE TITLE
There is Fabric WTHIT Update Notification for Quilt WTHIT in Mod Menu

### ISSUE THREAD

**Issue by Aleruslio** [badasintended/wthit#217]
### Describe the issue

![image](https://github.com/badasintended/wthit/assets/100682849/4b1f72b8-8d7b-46ec-b7a9-1164371cb7ae)
Minecraft 1.20.1/Quilt 0.19.1
WTHIT 8.1.1/Bad Packets 0.4.1
Mod Menu 7.1.0
So as you can see there is an update notification for Quilt version of WTHIT in mod menu (even though I was using the latest version of the mod) and the link for the update refers to Fabric version of WTHIT. I had this issue before (on 1.19.2), but then I could just download a Fabric mod update from the link and install it on Quilt. Now Minecraft doesn't run with Fabric WTHIT on Quilt.
Sorry for any mistakes and the sentence structure - my English pretty bad cause it's not my native language

### Log output and crash report

https://gist.github.com/Aleruslio/4c927c7103b8651d6ab68a6e46dd4483

**Comment by deirn** [comment]
I didn't add any version update check into WTHIT, so it must be from other mod. I think it's from Mod Menu, try asking there.
