### ISSUE TITLE
Some blocks in the blacklist cannot be deleted

### ISSUE THREAD

**Issue by hyplant** [badasintended/wthit#218]
### Describe the issue

According to [https://github.com/badasintended/wthit/issues/146](https://github.com/badasintended/wthit/issues/146) the blacklist can be edited.
But some blocks such as barriers and some entities such as snowballs cannot be removed from the blacklist.
Each time I restart the server ,they appear in the blacklist.

### Log output and crash report

无

### Additional context

无

**Comment by deirn** [comment]
I think 03b04d176fde7d27a0eb3179914f7acf6102b231 fixes this, though there's no release that contains it yet.
You can try the [build artifact](https://github.com/badasintended/wthit/suites/13837918888/artifacts/768384514) and see if the issue was fixed.
