### ISSUE TITLE
Waystone & SecurityCraft errors

### ISSUE THREAD

**Issue by ChenilleSaline** [badasintended/wthit#219]
### Describe the issue

When you launch the game, their is some error into log (but game doesn't crash) :
- Waystone instance registration
- Securitycraft dataprovider

### Log output and crash report

https://bin.disroot.org/?401d1132a296a58c#FmrD95sum6pJhreYFsg4S7VNLXRZARwcx8Uaz8brrVU2

### Additional context

- Forge Version : 47.1.0
- Minecraft Version : 1.20.1
- WTHIT Version : 8.1.1
- Waystone Version : 14.0.0
- Securitycraft Version : 1.9.7-beta1

**Comment by deirn** [comment]
Looks like Waystone's issue. The plugin definition has the pacakge wrong.

https://github.com/TwelveIterationMods/Waystones/blob/31a2f59aa48b79c9516275836e68a7584f307edf/shared/src/main/resources/waila_plugins.json#L3

@BlayTheNinth

**Comment by ChenilleSaline** [comment]
I dont understand : you've linked a 5 month ago commit but the error is still present today : how it's possible ?
In addition I don't think the 2 errors are same problem, are you sure ?

**Comment by deirn** [comment]
> I dont understand : you've linked a 5 month ago commit but the error is still present today : how it's possible ?

Because it's not changed to this day? Check the latest file.

> In addition I don't think the 2 errors are same problem, are you sure ?

Yes.

**Comment by ChenilleSaline** [comment]
> Because it's not changed to this day? Check the latest file.

No like I said I use the latest version of WTHIT and forge and minecraft and of course I've try to update before posting ;)

**Comment by deirn** [comment]
I know, but the latest Waystone version has that file...

**Comment by ChenilleSaline** [comment]
> I know, but the latest Waystone version has that file...


But I use also latest version of Waystone (& Security craft too)....
That's why I think you're closed this issue a little too quickly.

**Comment by deirn** [comment]
Inside the Waystone jar, it has the same `waila_plugins.json` file as the one I linked.
The file has the initializer value set as `net.blay09.mods.compat.WTHITIntegration`, which is wrong and the correct one should be `net.blay09.mods.waystones.compat.WTHITIntegration` instead.
You can see it for yourself, by opening the jar with WinRAR or other archiving programs.

I'm locking this issue as you don't seem to be willing to accept my findings, sorry.
