### ISSUE TITLE
Odd random crash

### ISSUE THREAD

**Issue by Tempest-5ky** [badasintended/wthit#223]
### Describe the issue

Game crashes for no reason that I could discern! Was simply walking normally.

Minecraft 1.19.2, WTHIT version 5.17.0

### Log output and crash report

https://mclo.gs/VtRoCb3

**Comment by deirn** [comment]
Your logs says you have WTHIT 5.16.1.

Update Megane to 8.4.2, or use Megane 8.5.0 with WTHIT 5.17.0.
