### ISSUE TITLE
Pet Owner information is no longer available on unmodded vanilla servers?

### ISSUE THREAD

**Issue by davepusey** [badasintended/wthit#227]
### Describe the issue

When I played on 1.19.0 using WTHIT 5.2.1 I could see Pet Owner information, even on unmodded vanilla servers, and without being an Op.

Now when playing on 1.20.1 using WTHIT 8.3.1 I can now longer see this information. Checking the config it says that Pet Owner requires to mod to be installed on the server.

Why has this changed? Is this a bug? Can this functionality be restored please?

### Log output and crash report

n/a

**Comment by deirn** [comment]
Since 1.19.4, the owner UUID is no longer synced to the client by the vanilla server. Now WTHIT needs to sync the UUID manually so the server must also have the mod.

**Comment by davepusey** [comment]
And yet mods like https://modrinth.com/mod/petowner can still do it fine. Yes, I could just use that mod instead, but it would be better to have it neatly integrated into the infobox.

**Comment by deirn** [comment]
Seems to not show on horses? https://github.com/PotatoPresident/PetOwner/issues/36

Yes I only tested the pet owner tooltip with horses 😅. If you accept that I guess I can make it defaults to client data.

**Comment by davepusey** [comment]
To be honest, the most common use case I have for this information was to find out who's cat or dog was sat down and in the way of something, so they could be asked to move it. Horses can be ridden by anyone, so not a concern for that use case.
