### ISSUE TITLE
Error occur when opening minecraft

### ISSUE THREAD

**Issue by eran0926** [badasintended/wthit#229]
### Describe the issue

when I opening minecraft 1.16.5 with forge, I always saw this
[Imgur](https://imgur.com/Kmqn5UG)

### Log output and crash report

https://gist.github.com/eran0926/4cf89b04e3ea0f39dfc32b69df8bde6b

### Additional context

It also occur when I only use wthit

**Comment by deirn** [comment]
Delete your config at `.minecraft/config/waila`.
