### ISSUE TITLE
Chat error notification "waila"

### ISSUE THREAD

**Issue by someonedeepintheinternet** [badasintended/wthit#231]
### Describe the issue

When looking at a furnace(any kind), I get a chat notification with an error. I'm not sure if this issue is from WTHIT or any other mod I use, but since it has "waila" in it I figured it would be related to the WTHIT mod.

Information beforehand: I use fabric-loader-0.14.21-1.20.1, wthit-fabric-8.3.1

Here's the full text:

Error on retrieving server data from provider
  mcp.mobius.waila.plugin.textile.provider.FluidStorageProvider$$Lambda$15313/0x0000000801d328c8

### Log output and crash report

https://gist.github.com/someonedeepintheinternet/057f943c917caa25f387fd715743407a

**Comment by deirn** [comment]
This should be fixed in OmniHopper's side.
