### ISSUE TITLE
Shadowy Item/Block Over the WTHIT UI

### ISSUE THREAD

**Issue by justwolfex** [badasintended/wthit#234]
### Describe the issue

I was testing mods (40 total) to create a personal modpack for myself and while doing so I noticed that there was a strange visual error/artifact (?) that made it difficult to make out what I was looking at with the mod. It looks like a shadowy version of the block I'm looking at overlaid over the UI.
<img width="877" alt="Screenshot 2023-10-14 122058" src="https://github.com/badasintended/wthit/assets/147938069/3ebc85ce-fea8-4f02-8070-91e16f872a9d">
<img width="827" alt="Screenshot 2023-10-14 122125" src="https://github.com/badasintended/wthit/assets/147938069/871942fa-fac2-4714-8904-3f10e3375ff2">
<img width="851" alt="Screenshot 2023-10-14 122405" src="https://github.com/badasintended/wthit/assets/147938069/8698b260-d24f-42ef-8c9d-e72666b9ac9a">

### Log output and crash report

https://gist.github.com/justwolfex/51e66f6dc4c152d60424de84f70c6b5e#file-latest-log & https://gist.github.com/justwolfex/b56cfae6b0645b586798db4ef81c62bd#file-crash-2023-10-14_12-34-55-client-txt

**Comment by deirn** [comment]
You have Jade alongside WTHIT. Both are WAILA/HWYLA forks. You need to choose either one.
