### ISSUE TITLE
Whaila error

### ISSUE THREAD

**Issue by TheTimiti** [badasintended/wthit#235]
### Describe the issue

After loading the game, such a picture appears in the main menu, and I would be happy to fix it myself, but my knowledge is no longer enough to fix this error somehow.

![image](https://github.com/badasintended/wthit/assets/147960158/c1f7d55a-370b-48e0-85b7-2602a3aa59a4)

### Log output and crash report

https://gist.github.com/TheTimiti/abd4307ada1a4b4b4ca70796cc574cd3

**Comment by deirn** [comment]
Looks like you have error on your config, delete the `config/waila` folder inside your game directory.
