### ISSUE TITLE
Custom names are not displayed

### ISSUE THREAD

**Issue by miraisoft-de** [badasintended/wthit#24]
Custom names of items should be displayed since [this](https://github.com/badasintended/wthit/commit/b4c645989c4f9dfa843f040ae39dc08dbf0bbe93) was resolved. However, I'm using mod version 2.5.4 (forge) and shulker boxes aren't displayed with the custom name.

**To Reproduce**
Change shulker box name with anvil. Place shulker box and look at it.

**Expected behavior**
Display custom name instead of general item name

**Setup**
- Minecraft: 1.16.4
- Forge: 35.1.4

**Comment by deirn** [comment]
did wthit also present on the server?

**Comment by miraisoft-de** [comment]
No. I thought it must be run only on client. I get the error message

> [main/FATAL] [minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        WTHIT (waila) has failed to load correctly
§7java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screen/Screen for invalid dist DEDICATED_SERVER

when I include it on server side.

**Comment by deirn** [comment]
oh well i guess that is different bug 😬

**Comment by deirn** [comment]
hmm i feel like i already fixed the crash... try version 2.7

**Comment by miraisoft-de** [comment]
I've just tested it in a single player world. The display works as intended there: showing custom names.

**Comment by miraisoft-de** [comment]
It works fine with version 2.7. Thanks.
