### ISSUE TITLE
Crashes on death with Bodies! Bodies! mod on Fabric 1.20.1

### ISSUE THREAD

**Issue by Poopooracoocoo** [badasintended/wthit#247]
### Describe the issue

Crashes on player death with inventory with [Bodies! Bodies!](https://modrinth.com/mod/bodies-bodies) mod

### Log output and crash report

https://gist.github.com/Poopooracoocoo/0a04959674d0f1843a370d88f3d74f72

### Additional context

Steps to reproduce: 
1. Launch game with mods
2. Create a world in creative
3. Add any item to your inventory
4. Execute `/kill @s`

Prompted by https://www.reddit.com/r/fabricmc/comments/1946u5k/minecraft_fabric_modpacket_crash/

**Comment by deirn** [comment]
This is more of Bodies Bodies issue.

In [here](https://github.com/GabrielOlvH/Bodies-Bodies/blob/6d81dfa5f31ef8ffb16d907d24c888da6cfb754b/src/main/java/me/steven/bodiesbodies/entity/DeadBodyEntityRenderer.java#L59), it calls for [`ClientPlayNetworkHandler`](https://maven.fabricmc.net/docs/yarn-1.20.1+build.10/net/minecraft/client/network/ClientPlayNetworkHandler.html#%3Cinit%3E(net.minecraft.client.MinecraftClient,net.minecraft.client.gui.screen.Screen,net.minecraft.network.ClientConnection,net.minecraft.client.network.ServerInfo,com.mojang.authlib.GameProfile,net.minecraft.client.util.telemetry.WorldSession)) with the client parameter as `null`.

**Comment by Blayung** [comment]
For anybody looking, it's really simple to fix, here's a fork: https://github.com/Blayung/Bodies-Bodies
