### ISSUE TITLE
Entity Timers

### ISSUE THREAD

**Issue by Diyagi** [badasintended/wthit#25]
Hello,

First, thanks for making this mod, it's indeed a lot better than the others.

Now, I would like to know if it is possible to put entity timers on this mod,

When I say entity timers, I mean to say, time until a cow can breed again, or, time until a baby cow grows up.

I remember that I saw this on another mod before, and I would be happy if this got implemented in this mod.
Thanks again for the mod and for the attention.

**Comment by deirn** [comment]
I'd say it's not in scope in base wthit, sorry. My view of the vanilla plugin is to take info that already showed to the player in one way or another (block state, container, action bar, etc) and make a tooltip about it. I also not feeling good about adding a feature that requires server-side (though I'm keeping what already done by TehNut). I'll let someone else make a plugin.
