### ISSUE TITLE
The built-in Harvestability plugin cannot be made to look like the discontinued mod WTHIT Harvestability

### ISSUE THREAD

**Issue by DarthCaesium** [badasintended/wthit#251]
### Enhancement

As far as I'm aware, no such option exists on the plugin to make it look like this. The plugin only offers me two total config options, and is nowhere as expansive as the discontinued mod.

**Comment by deirn** [comment]
What are the specific options that you want?

**Comment by DarthCaesium** [comment]
I want it to look exactly like the default look of WTHIT Harvestability.

**Comment by deirn** [comment]
The classic mode looks similar to it.

**Comment by DarthCaesium** [comment]
Is it exactly the same? If not, what parts are different, can I change it to be exactly the same, and how can I do that?

**Comment by deirn** [comment]
Try it for yourself and decide if it's good enough or not.

In terms of the default WTHIT harvestability, then yes, I'd say it looks similar enough. I based the classic mode from it, but I didn't copy its code as it's pretty bad (granted it's a decade old).
