### ISSUE TITLE
Interactic has a tooltip, this is not a compatibility issue with WTHIT, just confusing.

### ISSUE THREAD

**Issue by Barerock** [badasintended/wthit#252]
### Enhancement

I couldn't find another post for this issue, so here we are. I would like to eliminate the central item tooltip because it clutters the screen when everything else has been moved or modified to be as unintrusive as possible. I can already see the item readily, but even if I wanted this tooltip I would want the ability to move and customize it just like the block tooltip.

Thanks for the remake <3

**Comment by Barerock** [comment]
![image](https://github.com/badasintended/wthit/assets/38869993/8142d03e-2f36-455e-9582-2da471779d6c)
The central text is what I am having trouble with, and I haven't been able to turn it off. I did remove the aforementioned dual notation of registries. AKA, displaying "Minecraft Minecraft," or "Mod, Minecraft" sometimes.

**Comment by deirn** [comment]
The one that's on your crosshair? That's not from WTHIT. WTHIT item tooltip would be at the same place as the block tooltip on the left of your hotbar.

**Comment by Barerock** [comment]
> That's not from WTHIT.

I haven't added any others, and it obeys WTHIT config, such as the fix for double registries I mentioned above.

**Comment by Barerock** [comment]
As I suspected, it shows up with Interactic enabled.

**Comment by Barerock** [comment]
And is apparently linked to WTHIT somehow, config has options for turning tooltips off/on.
