### ISSUE TITLE
incompatibility with Jaiz Mobs

### ISSUE THREAD

**Issue by nickademas** [badasintended/wthit#260]
### Describe the issue

![obraz](https://github.com/badasintended/wthit/assets/46594867/3bd1aade-0090-4fcd-86c0-80354ce09032)
![obraz](https://github.com/badasintended/wthit/assets/46594867/61a4a9a8-53b0-4fbc-a275-5ba87b1dea3b)
this happens with every block

### Log output and crash report

https://gist.github.com/nickademas/9a82753f29844d8f606229af1422e334 https://gist.github.com/nickademas/fc63908e0f526500a7041bb2e8ce479f

**Comment by deirn** [comment]
This is more of Jaiz Mobs' issue, as its custom `ToolMaterial` implementation has `null` tag while it shouldn't.
