### ISSUE TITLE
An incorrect display when using MTR at the same time

### ISSUE THREAD

**Issue by ZhFrank** [badasintended/wthit#271]
### Describe the issue

When we using MTR and WTHIT at the same time, lower our heads, then, it will display "Minecraft Transit Railway", even there is nothing relat with MTR. As this picture, it displayed MTR when there was a grass block in fact.
<img width="1280" alt="微信图片_20240630163021" src="https://github.com/badasintended/wthit/assets/141153970/0d766feb-d215-4b96-960b-46ae63ca0c85">
Version:
Minecraft1.20.1-Fabric0.15.11
WTHIT v8.13.2
MTR v1.20-3.2.2-hotfix-1
Hope the above is helpful.

### Log output and crash report

May not need. And this won't lead the game crash.

### Additional context

Nothing need.

**Comment by deirn** [comment]
It's an issue that MTR should fix on their side.
https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/issues/341

They should either make a custom plugin or tag the entity with `waila:blacklist`
https://docs.bai.lol/wthit/plugin/adding_to_blacklist/
