### ISSUE TITLE
Cursed chest immediately disconnects us from our server

### ISSUE THREAD

**Issue by sleepyuwus** [badasintended/wthit#275]
### Describe the issue

I play on a server with a friend, and somehow he managed to curse one of his chests? This problem occurs to both of us.
When we look at the chest, we get disconnected. Moving our client-sided wthit-fabric-12.2.2 out of our mods folder fixed the issue for both of us.

Crazily enough, he blew up the first chest, but the issue returned on another chest that previously worked. (probably the first one he interacted with) Before he did we could both access the chest just fine. And also after we removed the mod there have not been any issues.

Mind you we use a handful of mods, so it could be an interaction thing. Unfortunately as long as this issue persists, we are unable to use the mod for now. I hope this helps someone.

### Log output and crash report

log output in additional context

### Additional context

[disconnect-2024-07-07_23.42.23-client.txt](https://github.com/user-attachments/files/16131099/disconnect-2024-07-07_23.42.23-client.txt)
[2024-07-08-4.log](https://github.com/user-attachments/files/16131147/2024-07-08-4.log)

**Comment by deirn** [comment]
Try disabling the tooltip, it should not trigger it if its hidden.
Can I get a data dump of the chest? run the `/data get block x y z` command.

**Comment by sleepyuwus** [comment]
Sorry for the late response.
SO. Obviously disabling the tooltip worked.
The data dump is probably not so important anymore because i figured out the problem. It is an interaction with this mod: https://modrinth.com/mod/universal-graves
When one of us dies, we get a grave compass that leads us to our grave. Normally this compass disappears if you pick up your stuff, so i didn't bother disabling the compass in the plugins options. If a grave compass is inside the chest, the tooltip probably cannot keep up? Something about that disconnects us immediately from the server. Grave compass inside chest = EVIL.

![Bild_2024-07-10_133624507](https://github.com/badasintended/wthit/assets/175032809/7cecda2c-c28d-453c-9ed6-cdcf9a970f04)

![Bild_2024-07-10_134845788](https://github.com/badasintended/wthit/assets/175032809/2217f787-b502-4a1c-9730-cfe2ee10ee29)

**Comment by deirn** [comment]
So it's from an item from a mod that uses Polymer, it seems to be related to server-only components.

CC: @Patbox, I need your input on this.

**Comment by Patbox** [comment]
Hmm, with Mojang's networking changes, it should convert correctly as long as it uses vanilla network itemstack codec and it uses vanilla packet payload system to write it.

**Comment by deirn** [comment]
Ah, does Polymer also mixin into vanilla item codec?
Since item NBT/component sync is optional in WTHIT, I don't use it.
https://github.com/badasintended/wthit/blob/ad453284c3cc5e1d3bae24df37fd3fcf35c722e7/src/pluginExtra/java/mcp/mobius/waila/plugin/extra/data/ItemDataImpl.java#L17-L50

**Comment by Patbox** [comment]
Looks like I missed a patch to DataComponentPatch.STREAM_CODEC / ComponentChanges.PACKET_CODEC. Will fix that on polymer side. Through you also should use `PacketCodecs.registry(RegistryKeys.ITEM)` (not sure yarn name) instead of [write/read]ById

**Comment by deirn** [comment]
Cool, I'll also change that. Thanks.
