### ISSUE TITLE
Incompatible with AE2 addon?

### ISSUE THREAD

**Issue by Barerock** [badasintended/wthit#288]
### Describe the issue

![image](https://github.com/user-attachments/assets/13d4c1ad-7f8e-4ff9-ad48-22b6caaeb228)

### Log output and crash report

https://gist.github.com/Barerock/8e85900ae36945feaa37bc5fa8b42329

### Additional context

Some mods have been updated, but I have disabled most and found that this error occurs regularly.

**Comment by Barerock** [comment]
I've deleted config\waila as well. This occurs on multiple versions, from 8.15.1 tp 8.15.0 on 1.20.1. I am testing more versions.

**Comment by Barerock** [comment]
8.14.0 does _not_ crash

**Comment by seancrain** [comment]
I've been getting a similar issue against both AE2 and ProjectE. Installing the newest WTHIT builds in their presence causes them to show this exact error on startup. I haven't tested 8.15.1 myself but it may well still be an issue.

[https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/8169](https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/8169)
[https://github.com/sinkillerj/ProjectE/issues/2359](https://github.com/sinkillerj/ProjectE/issues/2359)

**Comment by Barerock** [comment]
I do have AE2 as well. I will try starting latest WTHIT without AE2.

**Comment by seancrain** [comment]
I've just tested 8.15.1 against both AE2 and ProjectE. Those mods no longer crash when the only other mods installed are WTHIT and Bad Packets. There may be another mod installed that is still causing errors.

Still need to test it in a larger environment. Will update this post once I have done that.

**Comment by Barerock** [comment]
I have tested with over 300 mods minus AE2 and 3 AE2 addons and can confirm that it starts up without error. So, AE2 and PE definitely are causing this probably exclusively.

**Comment by seancrain** [comment]
I have just thrown 8.15.1 into my own modpack environment that has AE2, ProjectE, and 250 other mods, and I am not having any further crashes. What AE2 addons are you using?

**Comment by Barerock** [comment]
Ars Energistique, Create: Applied Kinetics. I will test separately.

**Comment by Barerock** [comment]
Okay suddenly it starts ayokay... I have no idea. I readded them 1 by 1.

**Comment by seancrain** [comment]
Very strange. I had a similar issue a few days ago. I was trying to figure out which mod of the set was causing the crash so I could report it, and encountered an error where if I had Mekanism, WTHIT 8.15.0, and two of my own mods, YogMod and NFM, installed alongside a couple others, something would break in the loading process and crash the game, but if each mod was installed independently alongside WTHIT, it would be fine. YogMod and NFM could be installed alongside Mekanism or WTHIT and it would work, but not all of them at once.

What makes that strange is that when I put them together with the entire modpack (removing AE2 and ProjectE before 8.15.1, of course), there were no loading problems at all. I couldn't figure out exactly what happened but maybe some strange issue like that is affecting your game,

**Comment by deirn** [comment]
The initial issue should be fixed in 5.30.1/8.15.1.
I'm not so sure about the others though, I need something reproducible...

**Comment by deirn** [comment]
Closing this issue, if you do find a way to reproduce the problem, please open another issue.
