### ISSUE TITLE
all assets show \u00A79\u00A7oMinecraft

### ISSUE THREAD

**Issue by superon** [badasintended/wthit#29]
**Describe the bug**
as the title says: 
https://imgur.com/SxfcbWK
Link to log:
https://pastebin.com/GfCbsj5E

**To Reproduce**
load game, look at things.

**Expected behavior**
i expect thing not to have \u00A79\u00A7oMinecraft in the "ToolTip"

**Setup**
Do not use Latest
- Minecraft: 1.16.5
- Fabric Loader: 0.11.1
- Fabric API 0.33.1+1.16

**Additional context**
could be a compat thing? i'm pretty tired

**Comment by deirn** [comment]
delete your config at `.minecraft/config/waila/waila.json`

**Comment by superon** [comment]
:) oh
