### ISSUE TITLE
Unable to show infos on item

### ISSUE THREAD

**Issue by VaporeonScripts** [badasintended/wthit#291]
### Describe the issue

[13Sep2024 18:06:07.672] [Render thread/ERROR] [mcp.mobius.waila.service.ApiService/]: [WTHIT] Unsolvable tier comparison!
Either one of [l2complements:requires_sculk_tool] or [minecraft:incorrect_for_diamond_tool] does not contain all entries from the other one.
The comparison is based on the assumption that lower tier's incorrect block tag contains all entries from higher tier's tag.
This was fine for Vanilla, but might be not match modded behavior.
Please open an issue at https://github.com/badasintended/wthit/issues

### Log output and crash report

https://mclo.gs/kj8ZOjq

### Additional context

![image](https://github.com/user-attachments/assets/74a27e22-57b9-426c-ba2d-34801fcd11f9)

**Comment by deirn** [comment]
The tag name `requires_sculk_tool` suggest that L2Components' author wrongly overriden the method that should've return the tag that includes the block that the tier **can't** mine.

The vanilla tier interface was changed in 1.20.5, before it has a method that returns tag that contains blocks that require the tier.

I would suggest also opening issue to L2Components side.

Cc: @lcy0x1

**Comment by VaporeonScripts** [comment]
i already did open the issue on l2components page, as a temp fix i noticed that disabling this makes the error disappear
![image](https://github.com/user-attachments/assets/373f6a0d-0c9d-4441-8661-08a46f63eaca)

**Comment by deirn** [comment]
Alright, thanks. Please also link this issue there so my comment can be seen by them.

**Comment by VaporeonScripts** [comment]
Idk how to do that

**Comment by deirn** [comment]
Just copy the link of this page.

**Comment by lcy0x1** [comment]
Thanks. I will fix it
