### ISSUE TITLE
Error in class

### ISSUE THREAD

**Issue by MathiasSvDK** [badasintended/wthit#292]
### Describe the issue

When looking at a block, i get this error
![image](https://github.com/user-attachments/assets/153db7ba-5d40-4531-a6a4-47b330fc2384)

Error log attached.
[error.txt](https://github.com/user-attachments/files/16997060/error.txt)

### Log output and crash report

ee

**Comment by MathiasSvDK** [comment]
Im on version 1.20.1 using version 8.15.1

**Comment by deirn** [comment]
Well, ain't this one stinks... Someone decided to return -1 as the tier level...

**Comment by MathiasSvDK** [comment]
But it does this for all blocks?
