### ISSUE TITLE
1.18.2: I got this error code "minecraft java The game crashed whilst unexpected error Error: java.lang.IllegalStateException: Already building!" and while looking through the crash report it said the suspected mod was wthit.

### ISSUE THREAD

**Issue by Baronblue53** [badasintended/wthit#298]
### Describe the issue

[crash-2024-10-08_00.08.19-client.txt](https://github.com/user-attachments/files/17288748/crash-2024-10-08_00.08.19-client.txt)

I only was able to understand the suspected mod portion of the report and nothing else. I am not a good with software so I don't know what the crash file is saying. 
I updated all mods, updated my drivers, and restarted my computer. The game loads up properly and I am able to access my world, but while it loads, it goes to the 'Loading Terrain' animation, to 'Joining World' then right back to 'Loading Terrain' and then crashes with the 'minecraft java The game crashed whilst unexpected error Error: java.lang.IllegalStateException: Already building!' and 'Exit Code: -1'. I don't know how to fix this issue.

### Log output and crash report

https://gist.github.com/Baronblue53/ba8b25329e22aa0e9e36c68800822bc6

**Comment by deirn** [comment]
Does this happen with only WTHIT and its dependencies?

**Comment by Baronblue53** [comment]
I tried disabling WTHIT and it still crashed. Is it possible WTHIT corrupted some other mods?

**Comment by deirn** [comment]
The issue stems from the other mod, essentially, that mod forgot to mark its rendering as finished.
There can only be one render call at a time, so when WTHIT tries to render, it fails because it is still marked as used by the troubling mod.

You need to figure out what mod it is, this is not a WTHIT issue.
