### ISSUE TITLE
Mob hearts use player heart texture instead

### ISSUE THREAD

**Issue by Cloud7050** [badasintended/wthit#30]
**Describe the bug**
Mob hearts in the tooltip use the player heart texture instead of the mob heart texture. But it correctly uses the mob heart outline texture. This is a bug also present from HWYLA, but I guess that's not getting fixed there.

**To Reproduce**
Use a resource pack where the mob hearts + outline look different from player hearts + outline.
Start the game and ensure mod config displays animals.
Spawn an animal like a pig and look at it.

**Expected behavior**
Mod tooltip should use mob heart texture + mob outline texture, instead of player heart texture + mob outline texture

**Setup**
- Minecraft: 1.16.5
- Fabric Loader: fabric-loader-0.11.1-1.16.5
- Fabric API: fabric-api-0.34.0+1.16

**Comment by deirn** [comment]
Is mob heart the pink one or the saddle one? If it's the latter then I'm not sure it'd make sense on hostile mob...
I'll probably make the outline use player's one

**Comment by Cloud7050** [comment]
![Screenshot 2021-05-13 002552](https://user-images.githubusercontent.com/44526554/118010692-dd4e9580-b381-11eb-81e3-dc96d779d0d4.jpg)

I have marked some boxes in the image above. For players, the mod uses green + blue. For mobs, it uses orange + blue. In vanilla, this works fine because the green and orange ones are the same texture. But for custom resource packs that change the hearts such that player and mob hearts have different outlines, orange + blue no longer works because they don't match, so you end up with a wrong-looking outline for mobs.

Your mentioned green + blue for both players & mobs would make sense if you find the "saddle" mob hearts to be odd. That would be an appreciated fix.

**Comment by deirn** [comment]
Yeah, it'll use the player outline. Mob hearts only make sense for rideable mobs since vanilla use it only for that
