### ISSUE TITLE
Why is the Forge mod loader being supported past 1.20.1?

### ISSUE THREAD

**Issue by JohnGoten** [badasintended/wthit#305]
### Describe the issue

I am sure you are well aware of the events that have gone down last year. It is but harmful to still provide updates for the mod loader in spite of NeoForge being a successor.
As such I kindly ask you to drop LexForge and move to full NeoForge support only.

Thanks.

### Log output and crash report

-

### Additional context

By not following in the footsteps of many reasonable individuals abandoning the LexForge mod loader past Minecraft version 1.20.1 you are one way or another proving the community how little care you seem to have for ethics.
I am glad to say that alternatives such as Jade by Snownee do not promote Lex' works since providing support for 1.20.2+ whilst building up both a better reputation and popularity amongst modded Minecraft players.

**Comment by deirn** [comment]
What ethics are you talking about?
I think I am reasonable here, it takes little code to support all platform, so why not?

**Comment by JohnGoten** [comment]
Whether or not it takes a single/few line(s) to provide LexForge support, the mod loader is not to be used past 1.20.1
Simple as that.

The ethics here are also kept simple:
Support Lex' work? Continue Forge support.
Don't want to promote their stuff but instead move on from that individual? Make the full switch to NeoForge. No inbetween or whatever you believe is apparently "good".


But thanks for directly providing me with a reason to not recommend this mod for anyone but instead use an alternative like the aforementioned Jade. (:

**Comment by deirn** [comment]
Sure.
