### ISSUE TITLE
Names Doesn't Display properly

### ISSUE THREAD

**Issue by jsr1976** [badasintended/wthit#32]
**Describe the bug**
When I look at any block the name doesn't show properly before the name there is some code showing, this happen since version 3.4.1 for 1.17

**To Reproduce**
Only face and look to a block

**Expected behavior**
The name whitout the rare code

**Setup**
Do not use Latest
- Minecraft: 20w17a
- Fabric Loader: 0.11.3
- Fabric API 0.34.1 

**Additional context**

**Comment by deirn** [comment]
Duplicate of #29, delete your config at `.minecraft/config/waila/waila.json`
