### ISSUE TITLE
Blacklisting

### ISSUE THREAD

**Issue by Brittank88** [badasintended/wthit#35]
I'd like to be able to blacklist entities, blocks, etc. that I wish for WTHIT to ignore. Here is an appropriate application for that:
![image](https://user-images.githubusercontent.com/24266948/118766866-5be68e00-b8c0-11eb-8cee-53f18fe5975d.png)

**Comment by deirn** [comment]
you can tag your block/entity with `waila:blacklist` and wthit will ignore it
https://github.com/badasintended/wthit/blob/1.16/common/src/main/resources/data/waila/tags/blocks/blacklist.json

**Comment by Brittank88** [comment]
Oh! Thank you. Wasn't aware of this (obviously 😜).
