### ISSUE TITLE
Flaky crash when placing shulker box

### ISSUE THREAD

**Issue by Nachtalb** [badasintended/wthit#38]
**Describe the bug**
Sometimes when I place a shulker box wthit throws an error that crashes the game. 
When I restart the game again I can usually place the shulker box again without a problem. Sadly I haven't found a way to make it 100% reproducible as it really only happens sometimes (maybe about 1/15 times or so it crashes). 

I do have some other mods installed and am playing on a server (which of course also has all the necessary mods incl. wthit). Haven't tried it in single player so idk bout that. 

Link to log:
https://bin.s.nachtalb.io/sukemuyabu.class

**To Reproduce**
Steps to reproduce the behaviour:
Place shulker box in survival => 💥 

**Expected behaviour**
well, I think that's obvious :) no crash

**Setup**
Do not use Latest
- Minecraft: 1.17
- Fabric Loader: 0.11.3
- Fabric API: 0.34.9+1.17

**Comment by deirn** [comment]
Yeah, can't seem to reproduce this, but I have an idea of what could cause it. Can you try [this file](https://github.com/badasintended/wthit/suites/2961412204/artifacts/66704148) and see if the issue is gone?

**Comment by Nachtalb** [comment]
I played some time now with the version you linked above and never had the issue again, so I guess whatever you did fixed it 👍 Thanks!
