### ISSUE TITLE
Jobless Villagers display as Nitwits

### ISSUE THREAD

**Issue by Arbee4ever** [badasintended/wthit#4]
#### What happens:
When looking at jobless villagers that aren't Nitwits wthit tells me they are Nitwits.

#### What you expected to happen:
It should display that these Villagers are Jobless Villagers and not Nitwits

#### Steps to reproduce:

1. Summon a Villager
2. Look at him with the mod activated

____
#### Affected Versions (Do *not* use "latest"):

- WTHIT: 2.2.0+1.16.5
- Minecraft: 1.16.4
- Fabric API: 0.29.4+1.16

#### Possible Conflicting Mods (Provide their version, as well)
None

**Comment by deirn** [comment]
It'll show them as simply `Villager`, since it's what vanilla do.
