### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by BruceWayne-DK** [badasintended/wthit#42]
https://gist.githubusercontent.com/natanfudge/f50bdea76dcd214b77bbeec400f79942/raw/4b83bfde9f0bec4e8e091cf1c3963482987a519f/crash.txt

**Comment by BruceWayne-DK** [comment]
Crash whenever I destroy a block

**Comment by deirn** [comment]
any reason why you're still in 21w18a?

**Comment by BruceWayne-DK** [comment]
That's the DOM Modpack version number for 1.17 release on the cureseforge

**Comment by deirn** [comment]
Well tell them to update then, I'm not gonna support snapshots if there's a release version. Open another issue if it persists on 1.17. Also please choose one of the issue templates if you can.
