### ISSUE TITLE
Simple Drawers Incompatibility

### ISSUE THREAD

**Issue by greensad** [badasintended/wthit#46]
**Describe the bug**
Crashes when placing any drawer.
Link to log: https://pastebin.com/mUsPA6hg

**To Reproduce**
Load a world and place any drawer.

**Expected behavior**
Place the drawer and not crash to menu.

**Setup**
- Minecraft: 1.16.5
- WTHIT: 2.10.4
- Fabric Loader: 0.11.6
- Fabric API: 0.35.1

**Additional context**
Using Hwyla allows simple drawers to work as expected without crashing.

**Comment by deirn** [comment]
looks like simple drawer is using internal renderer, try [this file](https://github.com/badasintended/wthit/suites/3038239833/artifacts/68976857) and see if it fixes it

**Comment by greensad** [comment]
> 
> 
> looks like simple drawer is using internal renderer, try [this file](https://github.com/badasintended/wthit/suites/3038239833/artifacts/68976857) and see if it fixes it

File did the trick, much appreciated! : )

**Comment by deirn** [comment]
alright, released 2.10.5, file should be available on CF soon
