### ISSUE TITLE
Could not find required mod

### ISSUE THREAD

**Issue by THEVERYLOL30** [badasintended/wthit#49]
**Describe the bug**
Could not find required mod: wthit requires fabric @[*]
Link to log:
![image](https://user-images.githubusercontent.com/86348485/123066312-3ba27580-d410-11eb-93e6-c0b906f1e511.png)

**To Reproduce**

**Expected behavior**

**Setup**
Do not use Latest
- Minecraft:1.17
- WTHIT:1.17 fabric
- Fabric Loader:Fabric loader
- Fabric API:IDK

**Additional context**

**Comment by deirn** [comment]
install fabric api https://www.curseforge.com/minecraft/mc-mods/fabric-api
