### ISSUE TITLE
Notblock displaying wrong notes

### ISSUE THREAD

**Issue by Oliver-makes-code** [badasintended/wthit#50]
**Describe the bug**
When I use a noteblock the note displayed will sometimes be off
It seems like it's skipping the Fs in the block and going straight to F#

**To Reproduce**
Place a noteblock and click it 11 times

**Expected behavior**
I expect the overlay to display F instead of F#

**Setup**
- Minecraft: 1.17
- WTHIT: 3.6.0
- Fabric Loader: 0.11.6
- Fabric API: 0.36.0

**Additional context**

**Comment by deirn** [comment]
already fixed with 3.6.1 (#48). next time check the latest version first.
