### ISSUE TITLE
Maven Mirror Request

### ISSUE THREAD

**Issue by hypherionmc** [badasintended/wthit#53]
Hi. This is not really related to the API or the mod, but is it okay with you if I mirror the api to my maven so that my team and I can have our own backup should any of your maven sources ever go down?

**Comment by deirn** [comment]
Of course! The real repo is in GitLab [here](https://gitlab.com/intended/maven/-/packages) 😂, the JFrog is only mirror of it and some dependencies.

**Comment by hypherionmc** [comment]
Thanks. So many mavens have been going down or changing addresses lately that time and time again we have failing builds because of that, so we want to have some form of backup for the dependencies we rely on. If you want, you're also welcome to use our maven as a delivery point. I don't mind
