### ISSUE TITLE
Not showing up at all

### ISSUE THREAD

**Issue by LimeShulkerBox** [badasintended/wthit#56]
**Describe the issue**
A clear and concise description of what your issue is.
The thing that should show up does not show up at all after fiddling with the config updating and downgrading and deleting the config.

**Log**
Regardless of whether it crashes or not, post your latest log as a [gist](https://gist.github.com/) and copy the link here.
[latest.log](https://github.com/badasintended/wthit/files/6877776/latest.log)

**To Reproduce**
Open the game and look at something

**Expected behavior**
The box including information showing up

**Additional context**
The mod list should be able to be found in the log if not I can send a list here

**Comment by deirn** [comment]
Did you enable the maintained mode on settings -> general? If so, you'd need to hold the key (default to numpad 1)

**Comment by LimeShulkerBox** [comment]
I did not, I fiddled with the keybinds anyway

**Comment by deirn** [comment]
Hmm, this is tricky. Can you send your config json?

**Comment by LimeShulkerBox** [comment]
As I said in the original I deleted it

**Comment by deirn** [comment]
Right, can you send me your mod folder so I can debug it?

**Comment by LimeShulkerBox** [comment]
It should be in the log I sent in the original message, if you don't like that method let me know of a way I can get it to you as it has quite a couple of mods

**Comment by deirn** [comment]
Getting the jar from you would save some time, some mods with weird id also hard to google :p. You can use a file host and send the link here or via discord `deirn#0100` if you don't want to make it public.

**Comment by LimeShulkerBox** [comment]
Alright I have added you on discord.

**Comment by deirn** [comment]
Resolved on discord, it was [Nyf's Expert Tweaks](https://www.curseforge.com/minecraft/mc-mods/nyfs-expert-tweaks)
