### ISSUE TITLE
redundant blockstates display between plugin/core and plugin/vanilla

### ISSUE THREAD

**Issue by catgirldoll** [badasintended/wthit#59]
The tooltip for bee nests and bee hives displays honey_level twice: once as "**Honey Level**" and once as "**honey_level**". This issue is due to redundant settings between `Waila Core` and `Minecraft` in config.

Similar redundancies apply to all blockstates (most of the available options) shown via `walia/plugin/vanilla/WaliaVanilla` when Waila Core is also showing blockstates. A possible solution would be to add an extra toggle/rule to not show specific blockstates in their raw form when they're selected in the WTHIT\Minecraft settings.

**Log:**
[MultiMC log](https://gist.github.com/snessim/fe903a1d668b4d7fdebc8e52b70c3067)

newly generated world;
fresh Minecraft 1.17.1 instance;
Fabric loader 0.11.6;
Fabric API 0.37.1+1.17;
WTHIT-Fabric 3.8.1
![placed hive](https://user-images.githubusercontent.com/20545957/127600550-3dadfc9f-0b48-4f1c-a8d1-4945a57fe758.png)
![placed nest](https://user-images.githubusercontent.com/20545957/127600552-8497c265-5d77-49b9-a6ff-ac58e3d09caa.png)

**Comment by snessim** [comment]
Similar redundancies apply to several blockstates shown by Waila core which have plugin settings under Minecraft
