### ISSUE TITLE
Numbers Display Strangely on Furnace

### ISSUE THREAD

**Issue by sweetsosweet** [badasintended/wthit#66]
### Describe the issue

Probably other blocks too, but when hovering over the furnace it has "e0" at the end of numbers:

![2021-08-30_19 08 34](https://user-images.githubusercontent.com/15041593/131417336-403e4b4e-02d0-41b9-83b4-51791509ce19.png)

### Log output

https://gist.github.com/sweetsosweet/62bf0199301b11033d34afa7e10cf7ea

**Comment by deirn** [comment]
Can you try [this file](https://github.com/badasintended/wthit/suites/3639762600/artifacts/88200490)? Use the file with no `-dev` or `-sources` prefix.

**Comment by sweetsosweet** [comment]
Yep, that fixed it perfectly, thank you!

![2021-08-31_18 59 54](https://user-images.githubusercontent.com/15041593/131586550-8ab1c1bb-2bc7-4126-bd79-90abda9bca35.png)

**Comment by deirn** [comment]
Fixed in b2fb9d27e99b580cc3cd309b7af1146f8e759f83
