### ISSUE TITLE
Too Much Displacement Due to Bossbars

### ISSUE THREAD

**Issue by Phoupraw** [badasintended/wthit#68]
### Describe the issue

Spawn more than 6 withers, and you can see only 6 bossbars showing, but the wthit box moving down for a distance of more than 6 bossbars.
In the following video, I used repeating command block to spawn 20 withers, where you can see the box moving down.
https://user-images.githubusercontent.com/50520903/132096691-8cb22824-6676-4182-b38f-86cf7708d448.mp4

### Log output

https://github.com/badasintended/wthit/files/7109836/2021-09-04-4.log.gz

**Comment by deirn** [comment]
Unrelated to the issue, but jeez that OpenGL error message spam 😅

**Comment by deirn** [comment]
The log with OpenGL spam removed: https://gist.github.com/deirn/52b5d1a0283d1ce8dd91cda3b66fdfd8
I guess you don't want your message edited by me, whatever.

**Comment by Phoupraw** [comment]
> The log with OpenGL spam removed: https://gist.github.com/deirn/52b5d1a0283d1ce8dd91cda3b66fdfd8
> I guess you don't want your message edited by me, whatever.

OK. The OpenGL spam does be the reason that I uploaded the zipped log. The log is too big and most of it is repeated.
