### ISSUE TITLE
Enchanted book mod name tooltip

### ISSUE THREAD

**Issue by jahirtrap** [badasintended/wthit#73]
### Describe the issue

When wthit mod is installed the mod name from enchanted books of various mods is not displayed correctly in the JEI
For example with the tombstone mod
With wthit mod (show Minecraft in mod name)
![2021-09-18_12 16 12](https://user-images.githubusercontent.com/75038202/133897483-740dd0a9-c91c-4c78-ac5d-dcd2e52fc3df.png)

Without wthit mod (show correct mod name)
![2021-09-18_12 14 28](https://user-images.githubusercontent.com/75038202/133897491-7afbe5bf-9088-4e1f-a95f-7efddef1607e.png)

### Log output

----

### Additional context

Mod version: [1.16.5] v2.10.7 forge.
I tested 2.5.4 version and apparently there if it works correctly, the problem only occurs in later versions.

**Comment by red2blue** [comment]
Wow I would've thought this was an REI issue/JEI issue! crazy that WTHIT is actually the one that did this.
