### ISSUE TITLE
NumberFormatException: For Input String "" log spam

### ISSUE THREAD

**Issue by Desempregago** [badasintended/wthit#81]
### Describe the issue

WTHIT 3.10.1
megane 5.5.0

Fabric 0.12.1 with API 0.41.3

### Log output

https://gist.github.com/Desempregago/d9633ff798dec710a20c887a523354c4

**Comment by deirn** [comment]
where's the full log?

**Comment by Desempregago** [comment]
too big
![image](https://user-images.githubusercontent.com/14002834/140393196-455121bd-cb1a-4a1b-ba48-04e45a3eed5c.png)

**Comment by Desempregago** [comment]
but it's mostly like this
![image](https://user-images.githubusercontent.com/14002834/140393280-38e4a7b4-8cc8-4deb-9be6-0404ed268231.png)

**Comment by deirn** [comment]
Hm, do you have infinitory installed?

**Comment by deirn** [comment]
Looking at your issue history, you probably have infinitory. I found this problematic mixin on it, that's probably what causes the spam.

https://github.com/Furgl/Infinitory/blob/b548fa4f4f082c100a9c36830bb0a9cb8fdb2c5c/src/main/java/furgl/infinitory/mixin/items/ItemRendererMixin.java

**Comment by Desempregago** [comment]
So it was Infinitory... Thanks for pointing out
