### ISSUE TITLE
[BUG] Incorrect mod displayed when looking at an item on the ground

### ISSUE THREAD

**Issue by Azercoco** [badasintended/wthit#88]
### Describe the issue

When looking at an item on the ground, WTHIT always display its mod as "Minecraft" when it's obviously not the case. (v 3.8.1) 
![image](https://user-images.githubusercontent.com/20425137/142274474-e188c75c-de54-413b-b130-36301e35ef95.png)

**Comment by deirn** [comment]
Already fixed in https://github.com/badasintended/wthit/commit/4df028da947571ccad7436e3b242f507a4ff888c (3.10.1)
