### ISSUE TITLE
Formatting string for registry names is ignored

### ISSUE THREAD

**Issue by 0x5c** [badasintended/wthit#9]
#### Issue Description:
The formatting string for registry names is ignored, and instead the registry name is always light grey (colour code 7). Text added before or after the `%s` placeholder is also ignored.

All other formatting strings work perfectly.

#### Steps to reproduce:

1. Set a custom formatting string for the registry name.
2. Issue is immediately apparent.

____
#### Affected Versions

- WTHIT: v2.2.1+1.16.5
- Minecraft: 1.16.4
- Fabric API: v0.30.3+1.16

**Comment by Razatop** [comment]
Did this ever get fixed? Still having it on 1.18.2 sadly.

**Comment by deirn** [comment]
> Did this ever get fixed? Still having it on 1.18.2 sadly.

It should be, please open another issue if it still happens on the latest version.
