### ISSUE TITLE
Add ability to disable tooltip's block/entity preview

### ISSUE THREAD

**Issue by Apis035** [badasintended/wthit#91]
![image](https://user-images.githubusercontent.com/53115851/144709324-ded3b233-3ef3-4c32-a59b-983490b46f11.png)
Would be nice if the preview on the left can be disabled to make hud cleaner since I don't really need it because the block can be viewed directly.

**Comment by deirn** [comment]
You can disable those in Plugin Settings > Waila Core > Show Item

**Comment by deirn** [comment]
4.3.1 renamed it to "Show Item Icon" to hopefully makes it more clear.

**Comment by Apis035** [comment]
Thanks, looks better now. I always thought that option is to show dropped item details.
