### ISSUE TITLE
[1.18.1] Wrong Harvest Levels displayed

### ISSUE THREAD

**Issue by red2blue** [badasintended/wthit#95]
### Describe the issue

https://github.com/TechReborn/TechReborn/issues/2656 
Latest WTHIT Release, Loader 0.12.12, MC 1.18.1

as you can see in the issue above and below ^ WTHIT is displaying the wrong harvest level for all modded ores. Not sure why. 

![image](https://user-images.githubusercontent.com/35115304/146650854-3f7e382b-9aac-4d3b-9d94-4384fe63c53d.png)

![image](https://user-images.githubusercontent.com/35115304/146650855-bdc2dfd3-725b-46a8-9f09-eaa02483adf7.png)

### Log output

[(https://pastebin.com/4f2W96qM)](https://pastebin.com/4f2W96qM)

**Comment by deirn** [comment]
WTHIT doesn't have a harvestable tooltip by its own, it came from a plugin called `can I mine this block? Open an issue there.

**Comment by red2blue** [comment]
Ah you're right. Apologies. Should've done that.
