### ISSUE TITLE
Red [Render thread/INFO] type logs

### ISSUE THREAD

**Issue by VivereYC** [badasintended/wthit#96]
### Describe the issue

I get some red [Render thread/INFO] type logs when I start Minecraft with WTHIT.

The [Render thread/INFO] Logs in red are:
[Render thread/INFO]: Discovered plugin waila:core at mcp.mobius.waila.plugin.core.WailaCore
[Render thread/INFO]: Discovered plugin waila:vanilla at mcp.mobius.waila.plugin.vanilla.WailaVanilla
[Render thread/INFO]: Registering plugin at mcp.mobius.waila.plugin.core.WailaCore
[Render thread/INFO]: Registering plugin at mcp.mobius.waila.plugin.vanilla.WailaVanilla

I also found a report about the same issue on the HWYLA Github page https://github.com/TehNut-Mods/HWYLA/issues/270 and I asked in the official MultiMC Discord help channel and someone mentioned it could be from logging to stderr instead of using the normal logging functionality.

Launcher: MultiMC 0.16.4-2998
Minecraft Version: 1.17.1
Fabric Modloader Version: 0.12.12
WTHIT Version: 3.11.12

### Log output

https://gist.github.com/JustVivere/ae6e78f0da282e9ae94a0614ea441c3f

### Additional context

a screenshot for the colors (ignore the yellow warning):
![image](https://user-images.githubusercontent.com/34337184/146771157-4f4857d1-c7ca-49fa-ab25-790f5cf7dab4.png)

**Comment by deirn** [comment]
Not sure why this happened, are other mods log do this? Pretty sure I used the correct logger.

**Comment by JustVivere** [comment]
so far I noticed it only with WHIT and megane. (tested it with all the mods enabled in the pack, which you can see in the logs)
