### ISSUE TITLE
Game crash occurs even if I am using the latest java/fabric/fabric_api/wthit

### ISSUE THREAD

**Issue by rjuven2401** [badasintended/wthit#97]
### Describe the issue

JAVA version: jdk-17.0.1_windows-x64_bin.exe
Fabric version: fabric-installer-0.10.2.exe
Fabric API version: fabric-api-0.45.0+1.18.jar
WTHIT mod version: wthit-fabric-4.4.0.jar

And when I run fabric-loader-1.18.1 with minecraft launcher, the following error occurs.

**The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'wthit'!
Exit Code: -1**

I also attached the crash report.

Sorry I am new to fabric, but when I run fabric_loader without WTHIT mod, minecraft does not give this error and the game starts fine. But if I put WTHIT mod then this crash occurs. Have no idea how I can fix this.

Also I am not familiar with github so label might not be correct. Sorry for that..

### Log output

[https://gist.github.com/rjuven2401/e644e50b45da436b7fe71b90cf0f4520](https://gist.github.com/rjuven2401/e644e50b45da436b7fe71b90cf0f4520)

**Comment by deirn** [comment]
Deleting `.minecraft/config/waila/waila_plugins.json` file should fix this issue. Probably happened because you have a config for older version of WTHIT.

**Comment by rjuven2401** [comment]
Thank you very much! The problem was fixed.
