### ISSUE TITLE
Regex Blacklist

### ISSUE THREAD

**Issue by deirn** [badasintended/wthit#99]

**Comment by twome** [comment]
Is it possible to add *all* vanilla Minecraft things to the blacklist without something like this regex functionality? I'd love to achieve this: WTHIT only ever shows up when you're looking at something added by a mod, *and* if it doesn't know which mod, it shows an unobtrusive "?" icon (or the acronym WTHIT?) to let you know it's missing compatibility for that mod. 

You could even add an achievement/advancement for actually finding an item WTHIT can't recognise ;)
